# SVGP Digital Twin — Proof of Concept

**Sprint 1 Deliverable** — Side-by-side comparison of `BayesianDTModel` (ExactGP) and `SVGPDigitalTwin` (Sparse Variational GP).

## What this notebook demonstrates

| | Bayesian (ExactGP) | SVGP |
|---|---|---|
| Kernel | ScaleKernel(RBF) + ConstantMean | Same |
| Training | Exact MLL, all data in memory | Variational ELBO, mini-batches |
| Complexity | O(n³) — fails at >10K pts | O(n·m²) — scales to 100K+ pts |
| Save/Load | Pickle (security risk) | torch.save (state_dict) |
| Interface | Direct BayesianDigitalTwin API | DTModel ABC |

### Data pipeline
1. **Generate UE tracks** — Gauss-Markov mobility model over a 3-cell deployment
2. **Synthesize RSRP** — log-distance path loss + lognormal shadow fading
3. **Feature engineering** — log_distance, relative_bearing (same as production pipeline)
4. **Train & predict** — both models, same data, same splits
5. **Compare** — MAE, prediction uncertainty, training time

### Key insight: accuracy vs. scale
SVGP does **not** automatically beat Bayesian on accuracy — it's an approximation.
On small data (< 1K points/cell), ExactGP is marginally more accurate.
On real deployment data (1K–100K+ points/cell), **Bayesian can't run** (O(n³) OOM),
while SVGP handles it trivially. That's where SVGP wins decisively.

In [1]:
import sys
from pathlib import Path

REPO_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))

In [2]:
import time
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from radp.digital_twin.utils import constants as c
from radp.digital_twin.utils.gis_tools import GISTools
from radp.utility.simulation_utils import seed_everything

from radp.digital_twin.rf.base_model import DTModel
from radp.digital_twin.rf.svgp.svgp_engine import SVGPDigitalTwin, SVGPTrainConfig

try:
    from radp.digital_twin.rf.bayesian.bayesian_engine import BayesianDigitalTwin
except ImportError:
    BayesianDigitalTwin = None

# Set to True only for small data. ExactGP scales cubically and can be very slow.
RUN_BAYESIAN = False

# Data paths
DATA_DIR = REPO_ROOT / "tmp" / "data" / "Million"

seed_everything(42)
print("Imports OK  |  DATA_DIR:", DATA_DIR)

Imports OK  |  DATA_DIR: /Users/tanzimfarhan/Desktop/Maveric/maveric_cloudly/maveric/tmp/data/Million

## 1. Load topology and config

In [3]:
topology_df = pd.read_csv(DATA_DIR / "topology.csv")
config_df = pd.read_csv(DATA_DIR / "config.csv")

# Current SVGPDigitalTwin requires antenna-height columns for feature engineering.
# The Million sample data does not include them, so use standard macro defaults.
DEFAULT_HTX_M = 30.0
DEFAULT_HRX_M = 1.5

site_configs_df = topology_df.merge(
    config_df[["cell_id", "cell_el_deg"]],
    on="cell_id",
    how="left",
)
site_configs_df[c.HTX] = site_configs_df.get(c.HTX, DEFAULT_HTX_M)
site_configs_df[c.HRX] = site_configs_df.get(c.HRX, DEFAULT_HRX_M)

TOPO_COLS = [
    c.CELL_ID,
    c.CELL_AZ_DEG,
    c.CELL_LAT,
    c.CELL_LON,
    c.CELL_CARRIER_FREQ_MHZ,
    c.CELL_EL_DEG,
    c.HTX,
    c.HRX,
    "site_id",
]
site_configs_df = site_configs_df[TOPO_COLS].reset_index(drop=True)

print(f"Loaded {len(site_configs_df)} cells across {site_configs_df.site_id.nunique()} sites")
site_configs_df.head()

Loaded 20 cells across 5 sites

,cell_id,cell_az_deg,cell_lat,cell_lon,cell_carrier_freq_mhz,cell_el_deg,hTx,hRx,site_id
0,cell_1_0,356.242833,38.71404,-125.836106,1800,8.706244,30.0,1.5,Site1
1,cell_1_1,91.504593,38.71404,-125.836106,2100,8.884467,30.0,1.5,Site1
2,cell_1_2,183.894878,38.71404,-125.836106,850,11.340435,30.0,1.5,Site1
3,cell_1_3,273.902744,38.71404,-125.836106,2100,4.271576,30.0,1.5,Site1
4,cell_2_0,355.585680,41.60740,-123.573457,2100,5.361171,30.0,1.5,Site2

## 2. Load and filter UE training data

In [4]:
ue_raw = pd.read_csv(DATA_DIR / "ue_training_data.csv")

raw_rows = len(ue_raw)
raw_cells = ue_raw[c.CELL_ID].nunique()
no_signal_rows = int((ue_raw["avg_rsrp"] <= -140).sum())
valid_signal_rows = int((ue_raw["avg_rsrp"] > -140).sum())
rows_per_cell = ue_raw.groupby(c.CELL_ID).size()

print(f"Raw UE rows      : {raw_rows:,}")
print(f"Cells            : {raw_cells}")
print(f"Rows per cell    : min={rows_per_cell.min():,}, max={rows_per_cell.max():,}")
print(f"avg_rsrp <= -140 : {no_signal_rows:,}")
print(f"avg_rsrp >  -140 : {valid_signal_rows:,}")
print(f"Columns          : {list(ue_raw.columns)}")

Raw UE rows      : 1,000,000
Cells            : 20
Rows per cell    : min=50,000, max=50,000
avg_rsrp <= -140 : 800,431
avg_rsrp >  -140 : 199,569
Columns          : ['cell_id', 'avg_rsrp', 'lon', 'lat', 'cell_el_deg']

In [5]:
# Select data scope for training.
# Use "ALL" for all sites, or "Site1" ... "Site5" for a smaller run.
DEMO_SITE = "ALL"

# Keep False for full 1M-row SVGP training/evaluation.
# Set True only if you explicitly want to exclude no-signal/out-of-range rows.
FILTER_NO_SIGNAL_ROWS = False

ue_model_input = ue_raw.copy()
if FILTER_NO_SIGNAL_ROWS:
    ue_model_input = ue_model_input[ue_model_input["avg_rsrp"] > -140].copy()

if DEMO_SITE == "ALL":
    demo_cell_ids = sorted(site_configs_df[c.CELL_ID].unique().tolist())
    site_configs_demo = site_configs_df.copy()
    ue_data_df = ue_model_input.copy()
else:
    demo_cell_ids = sorted(
        site_configs_df.loc[site_configs_df.site_id == DEMO_SITE, c.CELL_ID].tolist()
    )
    site_configs_demo = site_configs_df[site_configs_df[c.CELL_ID].isin(demo_cell_ids)].copy()
    ue_data_df = ue_model_input[ue_model_input[c.CELL_ID].isin(demo_cell_ids)].copy()

print(f"Scope: {DEMO_SITE}  ->  cells: {len(demo_cell_ids)}")
print(f"Total UE rows in scope: {len(ue_data_df):,}")
print(f"No-signal filtering enabled: {FILTER_NO_SIGNAL_ROWS}")
print("\nRows per site:")
print(
    ue_data_df.merge(site_configs_df[[c.CELL_ID, "site_id"]], on=c.CELL_ID, how="left")
    .groupby("site_id")
    .size()
    .to_string()
)
print("\nRows per cell:")
print(ue_data_df.groupby(c.CELL_ID).size().describe().round(0).to_string())
print("\nRSRP summary:")
print(ue_data_df.groupby(c.CELL_ID)["avg_rsrp"].describe().round(2).to_string())

Scope: ALL  ->  cells: 20
Total UE rows in scope: 1,000,000
No-signal filtering enabled: False

Rows per site:
site_id
Site1    200000
Site2    200000
Site3    200000
Site4    200000
Site5    200000

Rows per cell:
count       20.0
mean     50000.0
std          0.0
min      50000.0
25%      50000.0
50%      50000.0
75%      50000.0
max      50000.0

RSRP summary:
            count    mean    std    min    25%    50%    75%   max
cell_id
cell_1_0  50000.0 -127.66  27.56 -140.0 -140.0 -140.0 -140.0 -44.0
cell_1_1  50000.0 -128.26  26.63 -140.0 -140.0 -140.0 -140.0 -44.0
cell_1_2  50000.0 -127.40  27.90 -140.0 -140.0 -140.0 -140.0 -44.0
cell_1_3  50000.0 -127.88  27.21 -140.0 -140.0 -140.0 -140.0 -44.0
cell_2_0  50000.0 -130.35  22.45 -140.0 -140.0 -140.0 -140.0 -44.0
cell_2_1  50000.0 -130.00  22.83 -140.0 -140.0 -140.0 -140.0 -44.0
cell_2_2  50000.0 -130.41  22.45 -140.0 -140.0 -140.0 -140.0 -44.0
cell_2_3  50000.0 -130.41  22.60 -140.0 -140.0 -140.0 -140.0 -44.0
cell_3_0  50000.0 -128.37  26.44 -140.0 -140.0 -140.0 -140.0 -44.0
cell_3_1  50000.0 -128.48  26.25 -140.0 -140.0 -140.0 -140.0 -44.0
cell_3_2  50000.0 -128.10  26.88 -140.0 -140.0 -140.0 -140.0 -44.0
cell_3_3  50000.0 -126.39  29.31 -140.0 -140.0 -140.0 -140.0 -44.0
cell_4_0  50000.0 -128.49  26.17 -140.0 -140.0 -140.0 -140.0 -44.0
cell_4_1  50000.0 -126.94  28.45 -140.0 -140.0 -140.0 -140.0 -44.0
cell_4_2  50000.0 -127.37  27.84 -140.0 -140.0 -140.0 -140.0 -44.0
cell_4_3  50000.0 -128.40  26.31 -140.0 -140.0 -140.0 -140.0 -44.0
cell_5_0  50000.0 -130.08  22.77 -140.0 -140.0 -140.0 -140.0 -44.0
cell_5_1  50000.0 -130.41  22.48 -140.0 -140.0 -140.0 -140.0 -44.0
cell_5_2  50000.0 -129.42  23.88 -140.0 -140.0 -140.0 -140.0 -44.0
cell_5_3  50000.0 -130.63  22.09 -140.0 -140.0 -140.0 -140.0 -44.0

In [6]:
LAT_MIN = ue_data_df["lat"].min() - 0.02
LAT_MAX = ue_data_df["lat"].max() + 0.02
LON_MIN = ue_data_df["lon"].min() - 0.02
LON_MAX = ue_data_df["lon"].max() + 0.02

# Plot a sample only; training/evaluation below still uses the full scoped data.
PLOT_MAX_POINTS = 100_000
plot_df = ue_data_df.sample(n=min(PLOT_MAX_POINTS, len(ue_data_df)), random_state=42)

fig, ax = plt.subplots(figsize=(9, 7))
sc = ax.scatter(plot_df["lon"], plot_df["lat"],
                c=plot_df["avg_rsrp"], cmap="RdYlGn",
                vmin=-140, vmax=-50, s=4, alpha=0.35)

colors = ["#e74c3c", "#3498db", "#2ecc71", "#f39c12", "#9b59b6", "#16a085"]
for idx, (_, row) in enumerate(site_configs_demo.iterrows()):
    color = colors[idx % len(colors)]
    ax.scatter(row.cell_lon, row.cell_lat, s=120, marker="^",
               c=color, edgecolors="black", linewidths=1.0,
               zorder=10, label=row.cell_id if idx < 12 else None)

plt.colorbar(sc, ax=ax, label="avg_rsrp (dBm)")
ax.set_xlabel("Longitude"); ax.set_ylabel("Latitude")
ax.set_title(f"{DEMO_SITE} - UE measurement sample ({len(plot_df):,}/{len(ue_data_df):,} rows)")
ax.legend(loc="upper right", fontsize=7, ncol=2)
plt.tight_layout(); plt.show()

## 3. Feature engineering — log_distance and relative_bearing

In [7]:
print("Engineering SVGP features with current engine helpers...")
t0 = time.time()
training_frames_all = SVGPDigitalTwin.preprocess_ue_training_data(ue_data_df, site_configs_demo)
ue_data_df = pd.concat(training_frames_all, ignore_index=True)
print(f"Done in {time.time() - t0:.1f}s")

ue_data_df[[
    c.CELL_ID,
    c.LOG_DISTANCE,
    c.RELATIVE_BEARING,
    c.ANTENNA_GAIN,
    c.CELL_EL_DEG,
    "avg_rsrp",
]].head(6)

Engineering SVGP features with current engine helpers...
Done in 1.7s

,cell_id,log_distance,relative_bearing,antenna_gain,cell_el_deg,avg_rsrp
0,cell_1_0,12.000018,36.639876,-9.074891,8.706244,-140.0
1,cell_1_0,12.500556,119.046312,-9.083139,8.706244,-140.0
2,cell_1_0,12.500020,119.069101,-9.083132,8.706244,-140.0
3,cell_1_0,12.000068,36.600322,-9.074892,8.706244,-140.0
4,cell_1_0,12.835188,33.896051,-9.086751,8.706244,-140.0
5,cell_1_0,11.999424,36.644644,-9.074878,8.706244,-140.0

## 4. Train / test split — per cell

In [8]:
X_COLUMNS = [c.CELL_EL_DEG, c.LOG_DISTANCE, c.RELATIVE_BEARING, c.ANTENNA_GAIN]
Y_COLUMNS = ["avg_rsrp"]
TEST_SIZE = 0.30

# BDT/ExactGP is capped separately because it does not scale to the full data.
MAX_TRAIN_PER_CELL_BDT = 15000

# SVGP uses all available rows after the train/test split. Leave as None for full data.
MAX_TRAIN_PER_CELL_SVGP = None
MAX_TEST_PER_CELL = None


def maybe_sample(df: pd.DataFrame, max_rows: int | None, seed: int = 42) -> pd.DataFrame:
    if max_rows is None or len(df) <= max_rows:
        return df
    return df.sample(n=max_rows, random_state=seed)

train_map_bdt, train_map_svgp, test_map = {}, {}, {}
for cell_id, df in ue_data_df.groupby(c.CELL_ID):
    train, test = train_test_split(df, test_size=TEST_SIZE, random_state=42)

    train_bdt = maybe_sample(train, MAX_TRAIN_PER_CELL_BDT)
    train_svgp = maybe_sample(train, MAX_TRAIN_PER_CELL_SVGP)
    test = maybe_sample(test, MAX_TEST_PER_CELL)

    train_map_bdt[cell_id] = train_bdt.reset_index(drop=True)
    train_map_svgp[cell_id] = train_svgp.reset_index(drop=True)
    test_map[cell_id] = test.reset_index(drop=True)

cell_ids = sorted(test_map)
for cell_id in cell_ids:
    print(
        f"{cell_id}: "
        f"BDT train={len(train_map_bdt[cell_id]):>6,}, "
        f"SVGP train={len(train_map_svgp[cell_id]):>6,}, "
        f"test={len(test_map[cell_id]):>6,}"
    )

print("\nTotals:")
print(f"BDT train rows  : {sum(len(v) for v in train_map_bdt.values()):,}")
print(f"SVGP train rows : {sum(len(v) for v in train_map_svgp.values()):,}")
print(f"Test rows       : {sum(len(v) for v in test_map.values()):,}")

train_list_bdt = [train_map_bdt[cid] for cid in cell_ids]
train_list_svgp = [train_map_svgp[cid] for cid in cell_ids]
test_list = [test_map[cid] for cid in cell_ids]

cell_1_0: BDT train=15,000, SVGP train=35,000, test=15,000
cell_1_1: BDT train=15,000, SVGP train=35,000, test=15,000
cell_1_2: BDT train=15,000, SVGP train=35,000, test=15,000
cell_1_3: BDT train=15,000, SVGP train=35,000, test=15,000
cell_2_0: BDT train=15,000, SVGP train=35,000, test=15,000
cell_2_1: BDT train=15,000, SVGP train=35,000, test=15,000
cell_2_2: BDT train=15,000, SVGP train=35,000, test=15,000
cell_2_3: BDT train=15,000, SVGP train=35,000, test=15,000
cell_3_0: BDT train=15,000, SVGP train=35,000, test=15,000
cell_3_1: BDT train=15,000, SVGP train=35,000, test=15,000
cell_3_2: BDT train=15,000, SVGP train=35,000, test=15,000
cell_3_3: BDT train=15,000, SVGP train=35,000, test=15,000
cell_4_0: BDT train=15,000, SVGP train=35,000, test=15,000
cell_4_1: BDT train=15,000, SVGP train=35,000, test=15,000
cell_4_2: BDT train=15,000, SVGP train=35,000, test=15,000
cell_4_3: BDT train=15,000, SVGP train=35,000, test=15,000
cell_5_0: BDT train=15,000, SVGP train=35,000, test=15,000
cell_5_1: BDT train=15,000, SVGP train=35,000, test=15,000
cell_5_2: BDT train=15,000, SVGP train=35,000, test=15,000
cell_5_3: BDT train=15,000, SVGP train=35,000, test=15,000

Totals:
BDT train rows  : 300,000
SVGP train rows : 700,000
Test rows       : 300,000

In [9]:
x_max = {
    c.CELL_EL_DEG: 50,
    c.CELL_LAT: 90,
    c.CELL_LON: 180,
    c.LOG_DISTANCE: 12,
    c.RELATIVE_BEARING: 360,
    c.ANTENNA_GAIN: 40,
}
x_min = {
    c.CELL_EL_DEG: -10,
    c.CELL_LAT: -90,
    c.CELL_LON: -180,
    c.LOG_DISTANCE: 0,
    c.RELATIVE_BEARING: 0,
    c.ANTENNA_GAIN: -40,
}

## 5. Train BayesianDTModel (ExactGP)

In [10]:
bayesian_model_map = {}
bayesian_losses = {}
bayesian_train_time = 0.0
RUN_BAYESIAN = True
if RUN_BAYESIAN:
    if BayesianDigitalTwin is None:
        raise ImportError("BayesianDigitalTwin is unavailable in this checkout")

    t0 = time.time()
    for cell_id in cell_ids:
        train_df = train_map_bdt[cell_id]
        model = BayesianDigitalTwin([train_df], X_COLUMNS, Y_COLUMNS, x_max=x_max, x_min=x_min)
        loss = model.train_distributed_gpmodel(
            maxiter=35,
            lr=0.05,
            stopping_threshold=1e-4,
        )
        bayesian_model_map[cell_id] = model
        bayesian_losses[cell_id] = loss[loss != 0]
        print(
            f"  {cell_id}: {len(train_df):>5} pts, {len(bayesian_losses[cell_id])} iters, "
            f"final loss = {bayesian_losses[cell_id][-1]:.4f}"
        )

    bayesian_train_time = time.time() - t0
    print(f"\nBayesian total time: {bayesian_train_time:.2f}s")
else:
    print("Skipping Bayesian ExactGP. Set RUN_BAYESIAN = True for small comparison runs.")

[2026-04-28 00:16:14,669] INFO:  Iter 1/35 - Loss: 0.774 (delta=inf)
[2026-04-28 00:16:17,241] INFO:  Iter 2/35 - Loss: 0.756 (delta=-0.017663)
[2026-04-28 00:16:19,465] INFO:  Iter 3/35 - Loss: 0.738 (delta=-0.018303)
[2026-04-28 00:16:21,080] INFO:  Iter 4/35 - Loss: 0.720 (delta=-0.017858)
[2026-04-28 00:16:22,615] INFO:  Iter 5/35 - Loss: 0.702 (delta=-0.017940)
[2026-04-28 00:16:25,293] INFO:  Iter 6/35 - Loss: 0.684 (delta=-0.018237)
[2026-04-28 00:16:27,078] INFO:  Iter 7/35 - Loss: 0.665 (delta=-0.018569)
[2026-04-28 00:16:28,808] INFO:  Iter 8/35 - Loss: 0.647 (delta=-0.018264)
[2026-04-28 00:16:31,645] INFO:  Iter 9/35 - Loss: 0.629 (delta=-0.018326)
[2026-04-28 00:16:33,301] INFO:  Iter 10/35 - Loss: 0.610 (delta=-0.018891)
[2026-04-28 00:16:34,782] INFO:  Iter 11/35 - Loss: 0.592 (delta=-0.018251)
[2026-04-28 00:16:36,375] INFO:  Iter 12/35 - Loss: 0.572 (delta=-0.019169)
[2026-04-28 00:16:37,887] INFO:  Iter 13/35 - Loss: 0.554 (delta=-0.018859)
[2026-04-28 00:16:39,401] INFO:  Iter 14/35 - Loss: 0.535 (delta=-0.018643)
[2026-04-28 00:16:41,036] INFO:  Iter 15/35 - Loss: 0.515 (delta=-0.019505)
[2026-04-28 00:16:42,592] INFO:  Iter 16/35 - Loss: 0.497 (delta=-0.018655)
[2026-04-28 00:16:44,181] INFO:  Iter 17/35 - Loss: 0.477 (delta=-0.019641)
[2026-04-28 00:16:45,714] INFO:  Iter 18/35 - Loss: 0.458 (delta=-0.018708)
[2026-04-28 00:16:47,244] INFO:  Iter 19/35 - Loss: 0.439 (delta=-0.019328)
[2026-04-28 00:16:48,751] INFO:  Iter 20/35 - Loss: 0.421 (delta=-0.018503)
[2026-04-28 00:16:50,378] INFO:  Iter 21/35 - Loss: 0.400 (delta=-0.020472)
[2026-04-28 00:16:51,954] INFO:  Iter 22/35 - Loss: 0.381 (delta=-0.019214)
[2026-04-28 00:16:53,530] INFO:  Iter 23/35 - Loss: 0.361 (delta=-0.019483)
[2026-04-28 00:16:55,097] INFO:  Iter 24/35 - Loss: 0.343 (delta=-0.018535)
[2026-04-28 00:16:56,622] INFO:  Iter 25/35 - Loss: 0.323 (delta=-0.020165)
[2026-04-28 00:16:58,132] INFO:  Iter 26/35 - Loss: 0.303 (delta=-0.019360)
[2026-04-28 00:16:59,640] INFO:  Iter 27/35 - Loss: 0.285 (delta=-0.018556)
[2026-04-28 00:17:01,207] INFO:  Iter 28/35 - Loss: 0.265 (delta=-0.019822)
[2026-04-28 00:17:02,740] INFO:  Iter 29/35 - Loss: 0.245 (delta=-0.019671)
[2026-04-28 00:17:04,379] INFO:  Iter 30/35 - Loss: 0.226 (delta=-0.019470)
[2026-04-28 00:17:06,560] INFO:  Iter 31/35 - Loss: 0.207 (delta=-0.018808)
[2026-04-28 00:17:08,203] INFO:  Iter 32/35 - Loss: 0.188 (delta=-0.019150)
[2026-04-28 00:17:09,841] INFO:  Iter 33/35 - Loss: 0.168 (delta=-0.020183)
[2026-04-28 00:17:12,321] INFO:  Iter 34/35 - Loss: 0.149 (delta=-0.019239)
[2026-04-28 00:17:13,901] INFO:  Iter 35/35 - Loss: 0.132 (delta=-0.016204)

  cell_1_0: 15000 pts, 35 iters, final loss = 0.1323

[2026-04-28 00:17:15,493] INFO:  Iter 1/35 - Loss: 0.776 (delta=inf)
[2026-04-28 00:17:17,027] INFO:  Iter 2/35 - Loss: 0.758 (delta=-0.017493)
[2026-04-28 00:17:18,560] INFO:  Iter 3/35 - Loss: 0.741 (delta=-0.017496)
[2026-04-28 00:17:21,201] INFO:  Iter 4/35 - Loss: 0.723 (delta=-0.017692)
[2026-04-28 00:17:22,829] INFO:  Iter 5/35 - Loss: 0.705 (delta=-0.017793)
[2026-04-28 00:17:24,323] INFO:  Iter 6/35 - Loss: 0.687 (delta=-0.017762)
[2026-04-28 00:17:25,843] INFO:  Iter 7/35 - Loss: 0.669 (delta=-0.018076)
[2026-04-28 00:17:27,341] INFO:  Iter 8/35 - Loss: 0.651 (delta=-0.018161)
[2026-04-28 00:17:28,819] INFO:  Iter 9/35 - Loss: 0.633 (delta=-0.018198)
[2026-04-28 00:17:30,371] INFO:  Iter 10/35 - Loss: 0.615 (delta=-0.018215)
[2026-04-28 00:17:33,170] INFO:  Iter 11/35 - Loss: 0.596 (delta=-0.018348)
[2026-04-28 00:17:34,687] INFO:  Iter 12/35 - Loss: 0.578 (delta=-0.018520)
[2026-04-28 00:17:36,248] INFO:  Iter 13/35 - Loss: 0.559 (delta=-0.018717)
[2026-04-28 00:17:37,834] INFO:  Iter 14/35 - Loss: 0.541 (delta=-0.018165)
[2026-04-28 00:17:39,332] INFO:  Iter 15/35 - Loss: 0.522 (delta=-0.019189)
[2026-04-28 00:17:40,889] INFO:  Iter 16/35 - Loss: 0.503 (delta=-0.018795)
[2026-04-28 00:17:42,837] INFO:  Iter 17/35 - Loss: 0.484 (delta=-0.019079)
[2026-04-28 00:17:44,409] INFO:  Iter 18/35 - Loss: 0.466 (delta=-0.018374)
[2026-04-28 00:17:45,900] INFO:  Iter 19/35 - Loss: 0.447 (delta=-0.018803)
[2026-04-28 00:17:47,481] INFO:  Iter 20/35 - Loss: 0.428 (delta=-0.019271)
[2026-04-28 00:17:49,028] INFO:  Iter 21/35 - Loss: 0.409 (delta=-0.018739)
[2026-04-28 00:17:50,571] INFO:  Iter 22/35 - Loss: 0.390 (delta=-0.018888)
[2026-04-28 00:17:52,148] INFO:  Iter 23/35 - Loss: 0.371 (delta=-0.018924)
[2026-04-28 00:17:53,656] INFO:  Iter 24/35 - Loss: 0.352 (delta=-0.019173)
[2026-04-28 00:17:55,234] INFO:  Iter 25/35 - Loss: 0.333 (delta=-0.018822)
[2026-04-28 00:17:56,771] INFO:  Iter 26/35 - Loss: 0.313 (delta=-0.019656)
[2026-04-28 00:17:58,272] INFO:  Iter 27/35 - Loss: 0.295 (delta=-0.018373)
[2026-04-28 00:17:59,811] INFO:  Iter 28/35 - Loss: 0.276 (delta=-0.018685)
[2026-04-28 00:18:01,320] INFO:  Iter 29/35 - Loss: 0.258 (delta=-0.017954)
[2026-04-28 00:18:02,827] INFO:  Iter 30/35 - Loss: 0.239 (delta=-0.019481)
[2026-04-28 00:18:04,333] INFO:  Iter 31/35 - Loss: 0.221 (delta=-0.017738)
[2026-04-28 00:18:05,841] INFO:  Iter 32/35 - Loss: 0.202 (delta=-0.019025)
[2026-04-28 00:18:07,362] INFO:  Iter 33/35 - Loss: 0.184 (delta=-0.017883)
[2026-04-28 00:18:08,926] INFO:  Iter 34/35 - Loss: 0.166 (delta=-0.018492)
[2026-04-28 00:18:10,454] INFO:  Iter 35/35 - Loss: 0.148 (delta=-0.017648)

  cell_1_1: 15000 pts, 35 iters, final loss = 0.1481

[2026-04-28 00:18:12,108] INFO:  Iter 1/35 - Loss: 0.765 (delta=inf)
[2026-04-28 00:18:13,619] INFO:  Iter 2/35 - Loss: 0.748 (delta=-0.017690)
[2026-04-28 00:18:15,124] INFO:  Iter 3/35 - Loss: 0.730 (delta=-0.017887)
[2026-04-28 00:18:16,622] INFO:  Iter 4/35 - Loss: 0.712 (delta=-0.017948)
[2026-04-28 00:18:18,145] INFO:  Iter 5/35 - Loss: 0.694 (delta=-0.018219)
[2026-04-28 00:18:19,688] INFO:  Iter 6/35 - Loss: 0.675 (delta=-0.018179)
[2026-04-28 00:18:21,202] INFO:  Iter 7/35 - Loss: 0.657 (delta=-0.018481)
[2026-04-28 00:18:22,788] INFO:  Iter 8/35 - Loss: 0.638 (delta=-0.018700)
[2026-04-28 00:18:24,306] INFO:  Iter 9/35 - Loss: 0.620 (delta=-0.018500)
[2026-04-28 00:18:25,832] INFO:  Iter 10/35 - Loss: 0.601 (delta=-0.018849)
[2026-04-28 00:18:27,351] INFO:  Iter 11/35 - Loss: 0.582 (delta=-0.018915)
[2026-04-28 00:18:28,930] INFO:  Iter 12/35 - Loss: 0.563 (delta=-0.019122)
[2026-04-28 00:18:30,511] INFO:  Iter 13/35 - Loss: 0.544 (delta=-0.019161)
[2026-04-28 00:18:32,163] INFO:  Iter 14/35 - Loss: 0.524 (delta=-0.019504)
[2026-04-28 00:18:33,735] INFO:  Iter 15/35 - Loss: 0.505 (delta=-0.019389)
[2026-04-28 00:18:35,298] INFO:  Iter 16/35 - Loss: 0.485 (delta=-0.019707)
[2026-04-28 00:18:36,817] INFO:  Iter 17/35 - Loss: 0.467 (delta=-0.018505)
[2026-04-28 00:18:38,322] INFO:  Iter 18/35 - Loss: 0.445 (delta=-0.021153)
[2026-04-28 00:18:39,825] INFO:  Iter 19/35 - Loss: 0.426 (delta=-0.019217)
[2026-04-28 00:18:42,414] INFO:  Iter 20/35 - Loss: 0.406 (delta=-0.019805)
[2026-04-28 00:18:43,967] INFO:  Iter 21/35 - Loss: 0.386 (delta=-0.019935)
[2026-04-28 00:18:45,472] INFO:  Iter 22/35 - Loss: 0.366 (delta=-0.020272)
[2026-04-28 00:18:47,024] INFO:  Iter 23/35 - Loss: 0.346 (delta=-0.020105)
[2026-04-28 00:18:48,595] INFO:  Iter 24/35 - Loss: 0.326 (delta=-0.020340)
[2026-04-28 00:18:50,120] INFO:  Iter 25/35 - Loss: 0.306 (delta=-0.020019)
[2026-04-28 00:18:51,710] INFO:  Iter 26/35 - Loss: 0.285 (delta=-0.020247)
[2026-04-28 00:18:53,222] INFO:  Iter 27/35 - Loss: 0.266 (delta=-0.019807)
[2026-04-28 00:18:54,781] INFO:  Iter 28/35 - Loss: 0.245 (delta=-0.020368)
[2026-04-28 00:18:56,387] INFO:  Iter 29/35 - Loss: 0.225 (delta=-0.019928)
[2026-04-28 00:18:57,914] INFO:  Iter 30/35 - Loss: 0.205 (delta=-0.020720)
[2026-04-28 00:18:59,422] INFO:  Iter 31/35 - Loss: 0.186 (delta=-0.018843)
[2026-04-28 00:19:00,979] INFO:  Iter 32/35 - Loss: 0.165 (delta=-0.020420)
[2026-04-28 00:19:02,599] INFO:  Iter 33/35 - Loss: 0.145 (delta=-0.020026)
[2026-04-28 00:19:04,128] INFO:  Iter 34/35 - Loss: 0.125 (delta=-0.020297)
[2026-04-28 00:19:05,641] INFO:  Iter 35/35 - Loss: 0.106 (delta=-0.019471)

  cell_1_2: 15000 pts, 35 iters, final loss = 0.1056

[2026-04-28 00:19:07,215] INFO:  Iter 1/35 - Loss: 0.775 (delta=inf)
[2026-04-28 00:19:08,716] INFO:  Iter 2/35 - Loss: 0.757 (delta=-0.017724)
[2026-04-28 00:19:11,257] INFO:  Iter 3/35 - Loss: 0.739 (delta=-0.017656)
[2026-04-28 00:19:12,779] INFO:  Iter 4/35 - Loss: 0.722 (delta=-0.017661)
[2026-04-28 00:19:14,382] INFO:  Iter 5/35 - Loss: 0.704 (delta=-0.018080)
[2026-04-28 00:19:16,042] INFO:  Iter 6/35 - Loss: 0.685 (delta=-0.018123)
[2026-04-28 00:19:18,587] INFO:  Iter 7/35 - Loss: 0.667 (delta=-0.018069)
[2026-04-28 00:19:20,149] INFO:  Iter 8/35 - Loss: 0.649 (delta=-0.018248)
[2026-04-28 00:19:21,816] INFO:  Iter 9/35 - Loss: 0.631 (delta=-0.018288)
[2026-04-28 00:19:23,359] INFO:  Iter 10/35 - Loss: 0.612 (delta=-0.018458)
[2026-04-28 00:19:24,898] INFO:  Iter 11/35 - Loss: 0.593 (delta=-0.018940)
[2026-04-28 00:19:26,493] INFO:  Iter 12/35 - Loss: 0.575 (delta=-0.018342)
[2026-04-28 00:19:28,024] INFO:  Iter 13/35 - Loss: 0.556 (delta=-0.018815)
[2026-04-28 00:19:29,552] INFO:  Iter 14/35 - Loss: 0.537 (delta=-0.018924)
[2026-04-28 00:19:32,283] INFO:  Iter 15/35 - Loss: 0.519 (delta=-0.018850)
[2026-04-28 00:19:33,864] INFO:  Iter 16/35 - Loss: 0.499 (delta=-0.019558)
[2026-04-28 00:19:35,451] INFO:  Iter 17/35 - Loss: 0.480 (delta=-0.018753)
[2026-04-28 00:19:36,978] INFO:  Iter 18/35 - Loss: 0.461 (delta=-0.019299)
[2026-04-28 00:19:38,518] INFO:  Iter 19/35 - Loss: 0.442 (delta=-0.018810)
[2026-04-28 00:19:40,047] INFO:  Iter 20/35 - Loss: 0.423 (delta=-0.019223)
[2026-04-28 00:19:42,664] INFO:  Iter 21/35 - Loss: 0.403 (delta=-0.019523)
[2026-04-28 00:19:44,193] INFO:  Iter 22/35 - Loss: 0.384 (delta=-0.018898)
[2026-04-28 00:19:45,685] INFO:  Iter 23/35 - Loss: 0.365 (delta=-0.019908)
[2026-04-28 00:19:47,245] INFO:  Iter 24/35 - Loss: 0.346 (delta=-0.018893)
[2026-04-28 00:19:48,841] INFO:  Iter 25/35 - Loss: 0.326 (delta=-0.019910)
[2026-04-28 00:19:50,356] INFO:  Iter 26/35 - Loss: 0.306 (delta=-0.019773)
[2026-04-28 00:19:51,897] INFO:  Iter 27/35 - Loss: 0.286 (delta=-0.019767)
[2026-04-28 00:19:53,540] INFO:  Iter 28/35 - Loss: 0.267 (delta=-0.018770)
[2026-04-28 00:19:56,103] INFO:  Iter 29/35 - Loss: 0.248 (delta=-0.019530)
[2026-04-28 00:19:57,851] INFO:  Iter 30/35 - Loss: 0.228 (delta=-0.019802)
[2026-04-28 00:19:59,530] INFO:  Iter 31/35 - Loss: 0.210 (delta=-0.017984)
[2026-04-28 00:20:01,096] INFO:  Iter 32/35 - Loss: 0.189 (delta=-0.021351)
[2026-04-28 00:20:02,587] INFO:  Iter 33/35 - Loss: 0.167 (delta=-0.021450)
[2026-04-28 00:20:04,148] INFO:  Iter 34/35 - Loss: 0.148 (delta=-0.019686)
[2026-04-28 00:20:05,660] INFO:  Iter 35/35 - Loss: 0.127 (delta=-0.020256)

  cell_1_3: 15000 pts, 35 iters, final loss = 0.1274

[2026-04-28 00:20:07,225] INFO:  Iter 1/35 - Loss: 0.769 (delta=inf)
[2026-04-28 00:20:08,728] INFO:  Iter 2/35 - Loss: 0.751 (delta=-0.018007)
[2026-04-28 00:20:10,247] INFO:  Iter 3/35 - Loss: 0.733 (delta=-0.018384)
[2026-04-28 00:20:11,755] INFO:  Iter 4/35 - Loss: 0.715 (delta=-0.018238)
[2026-04-28 00:20:13,282] INFO:  Iter 5/35 - Loss: 0.696 (delta=-0.018578)
[2026-04-28 00:20:14,892] INFO:  Iter 6/35 - Loss: 0.678 (delta=-0.018177)
[2026-04-28 00:20:16,442] INFO:  Iter 7/35 - Loss: 0.659 (delta=-0.018820)
[2026-04-28 00:20:17,967] INFO:  Iter 8/35 - Loss: 0.640 (delta=-0.019105)
[2026-04-28 00:20:19,493] INFO:  Iter 9/35 - Loss: 0.621 (delta=-0.018721)
[2026-04-28 00:20:21,034] INFO:  Iter 10/35 - Loss: 0.602 (delta=-0.019188)
[2026-04-28 00:20:22,574] INFO:  Iter 11/35 - Loss: 0.583 (delta=-0.019143)
[2026-04-28 00:20:24,141] INFO:  Iter 12/35 - Loss: 0.564 (delta=-0.019253)
[2026-04-28 00:20:25,660] INFO:  Iter 13/35 - Loss: 0.544 (delta=-0.019320)
[2026-04-28 00:20:27,244] INFO:  Iter 14/35 - Loss: 0.525 (delta=-0.019352)
[2026-04-28 00:20:28,759] INFO:  Iter 15/35 - Loss: 0.506 (delta=-0.019387)
[2026-04-28 00:20:30,397] INFO:  Iter 16/35 - Loss: 0.486 (delta=-0.019702)
[2026-04-28 00:20:33,021] INFO:  Iter 17/35 - Loss: 0.466 (delta=-0.019748)
[2026-04-28 00:20:34,568] INFO:  Iter 18/35 - Loss: 0.446 (delta=-0.020423)
[2026-04-28 00:20:36,140] INFO:  Iter 19/35 - Loss: 0.426 (delta=-0.019135)
[2026-04-28 00:20:37,758] INFO:  Iter 20/35 - Loss: 0.406 (delta=-0.020835)
[2026-04-28 00:20:39,302] INFO:  Iter 21/35 - Loss: 0.386 (delta=-0.020073)
[2026-04-28 00:20:40,839] INFO:  Iter 22/35 - Loss: 0.365 (delta=-0.020469)
[2026-04-28 00:20:42,367] INFO:  Iter 23/35 - Loss: 0.345 (delta=-0.020172)
[2026-04-28 00:20:43,896] INFO:  Iter 24/35 - Loss: 0.324 (delta=-0.020945)
[2026-04-28 00:20:45,439] INFO:  Iter 25/35 - Loss: 0.304 (delta=-0.020242)
[2026-04-28 00:20:47,007] INFO:  Iter 26/35 - Loss: 0.282 (delta=-0.021390)
[2026-04-28 00:20:48,559] INFO:  Iter 27/35 - Loss: 0.261 (delta=-0.021009)
[2026-04-28 00:20:50,105] INFO:  Iter 28/35 - Loss: 0.240 (delta=-0.021266)
[2026-04-28 00:20:51,628] INFO:  Iter 29/35 - Loss: 0.219 (delta=-0.021329)
[2026-04-28 00:20:53,226] INFO:  Iter 30/35 - Loss: 0.193 (delta=-0.025270)
[2026-04-28 00:20:54,763] INFO:  Iter 31/35 - Loss: 0.173 (delta=-0.020815)
[2026-04-28 00:20:56,359] INFO:  Iter 32/35 - Loss: 0.154 (delta=-0.018277)
[2026-04-28 00:20:57,889] INFO:  Iter 33/35 - Loss: 0.127 (delta=-0.027221)
[2026-04-28 00:20:59,400] INFO:  Iter 34/35 - Loss: 0.101 (delta=-0.025857)
[2026-04-28 00:21:00,968] INFO:  Iter 35/35 - Loss: 0.081 (delta=-0.020124)

  cell_2_0: 15000 pts, 35 iters, final loss = 0.0812

[2026-04-28 00:21:02,487] INFO:  Iter 1/35 - Loss: 0.770 (delta=inf)
[2026-04-28 00:21:03,991] INFO:  Iter 2/35 - Loss: 0.751 (delta=-0.018481)
[2026-04-28 00:21:05,487] INFO:  Iter 3/35 - Loss: 0.733 (delta=-0.018449)
[2026-04-28 00:21:06,980] INFO:  Iter 4/35 - Loss: 0.714 (delta=-0.018928)
[2026-04-28 00:21:08,502] INFO:  Iter 5/35 - Loss: 0.695 (delta=-0.018861)
[2026-04-28 00:21:10,014] INFO:  Iter 6/35 - Loss: 0.676 (delta=-0.018773)
[2026-04-28 00:21:11,610] INFO:  Iter 7/35 - Loss: 0.657 (delta=-0.019080)
[2026-04-28 00:21:13,117] INFO:  Iter 8/35 - Loss: 0.638 (delta=-0.019032)
[2026-04-28 00:21:14,646] INFO:  Iter 9/35 - Loss: 0.619 (delta=-0.019220)
[2026-04-28 00:21:16,167] INFO:  Iter 10/35 - Loss: 0.600 (delta=-0.018849)
[2026-04-28 00:21:17,685] INFO:  Iter 11/35 - Loss: 0.580 (delta=-0.019612)
[2026-04-28 00:21:19,189] INFO:  Iter 12/35 - Loss: 0.561 (delta=-0.019552)
[2026-04-28 00:21:20,822] INFO:  Iter 13/35 - Loss: 0.541 (delta=-0.019429)
[2026-04-28 00:21:22,390] INFO:  Iter 14/35 - Loss: 0.522 (delta=-0.019684)
[2026-04-28 00:21:23,905] INFO:  Iter 15/35 - Loss: 0.502 (delta=-0.019456)
[2026-04-28 00:21:25,499] INFO:  Iter 16/35 - Loss: 0.482 (delta=-0.020212)
[2026-04-28 00:21:27,060] INFO:  Iter 17/35 - Loss: 0.462 (delta=-0.019855)
[2026-04-28 00:21:28,567] INFO:  Iter 18/35 - Loss: 0.443 (delta=-0.019463)
[2026-04-28 00:21:30,081] INFO:  Iter 19/35 - Loss: 0.422 (delta=-0.020280)
[2026-04-28 00:21:32,693] INFO:  Iter 20/35 - Loss: 0.403 (delta=-0.019710)
[2026-04-28 00:21:34,300] INFO:  Iter 21/35 - Loss: 0.382 (delta=-0.020480)
[2026-04-28 00:21:35,875] INFO:  Iter 22/35 - Loss: 0.362 (delta=-0.020031)
[2026-04-28 00:21:37,391] INFO:  Iter 23/35 - Loss: 0.340 (delta=-0.021652)
[2026-04-28 00:21:38,892] INFO:  Iter 24/35 - Loss: 0.320 (delta=-0.020261)
[2026-04-28 00:21:40,413] INFO:  Iter 25/35 - Loss: 0.300 (delta=-0.020474)
[2026-04-28 00:21:41,921] INFO:  Iter 26/35 - Loss: 0.279 (delta=-0.020813)
[2026-04-28 00:21:43,476] INFO:  Iter 27/35 - Loss: 0.259 (delta=-0.020312)
[2026-04-28 00:21:45,185] INFO:  Iter 28/35 - Loss: 0.237 (delta=-0.021687)
[2026-04-28 00:21:46,745] INFO:  Iter 29/35 - Loss: 0.216 (delta=-0.020643)
[2026-04-28 00:21:48,263] INFO:  Iter 30/35 - Loss: 0.195 (delta=-0.021459)
[2026-04-28 00:21:49,774] INFO:  Iter 31/35 - Loss: 0.174 (delta=-0.020874)
[2026-04-28 00:21:51,295] INFO:  Iter 32/35 - Loss: 0.152 (delta=-0.021616)
[2026-04-28 00:21:52,879] INFO:  Iter 33/35 - Loss: 0.129 (delta=-0.023174)
[2026-04-28 00:21:54,406] INFO:  Iter 34/35 - Loss: 0.106 (delta=-0.022883)
[2026-04-28 00:21:56,927] INFO:  Iter 35/35 - Loss: 0.082 (delta=-0.024377)

  cell_2_1: 15000 pts, 35 iters, final loss = 0.0819

[2026-04-28 00:21:58,446] INFO:  Iter 1/35 - Loss: 0.770 (delta=inf)
[2026-04-28 00:21:59,921] INFO:  Iter 2/35 - Loss: 0.751 (delta=-0.018483)
[2026-04-28 00:22:01,419] INFO:  Iter 3/35 - Loss: 0.733 (delta=-0.018344)
[2026-04-28 00:22:02,905] INFO:  Iter 4/35 - Loss: 0.715 (delta=-0.018316)
[2026-04-28 00:22:04,379] INFO:  Iter 5/35 - Loss: 0.696 (delta=-0.018738)
[2026-04-28 00:22:05,861] INFO:  Iter 6/35 - Loss: 0.677 (delta=-0.018654)
[2026-04-28 00:22:07,396] INFO:  Iter 7/35 - Loss: 0.659 (delta=-0.018447)
[2026-04-28 00:22:08,885] INFO:  Iter 8/35 - Loss: 0.640 (delta=-0.018868)
[2026-04-28 00:22:10,374] INFO:  Iter 9/35 - Loss: 0.621 (delta=-0.019073)
[2026-04-28 00:22:12,134] INFO:  Iter 10/35 - Loss: 0.602 (delta=-0.018908)
[2026-04-28 00:22:13,719] INFO:  Iter 11/35 - Loss: 0.583 (delta=-0.018544)
[2026-04-28 00:22:15,229] INFO:  Iter 12/35 - Loss: 0.564 (delta=-0.019475)
[2026-04-28 00:22:16,736] INFO:  Iter 13/35 - Loss: 0.545 (delta=-0.019301)
[2026-04-28 00:22:18,278] INFO:  Iter 14/35 - Loss: 0.525 (delta=-0.019265)
[2026-04-28 00:22:19,822] INFO:  Iter 15/35 - Loss: 0.506 (delta=-0.019343)
[2026-04-28 00:22:21,344] INFO:  Iter 16/35 - Loss: 0.486 (delta=-0.019652)
[2026-04-28 00:22:22,885] INFO:  Iter 17/35 - Loss: 0.467 (delta=-0.019625)
[2026-04-28 00:22:24,398] INFO:  Iter 18/35 - Loss: 0.447 (delta=-0.019827)
[2026-04-28 00:22:27,011] INFO:  Iter 19/35 - Loss: 0.427 (delta=-0.019683)
[2026-04-28 00:22:28,613] INFO:  Iter 20/35 - Loss: 0.407 (delta=-0.019726)
[2026-04-28 00:22:30,172] INFO:  Iter 21/35 - Loss: 0.387 (delta=-0.020280)
[2026-04-28 00:22:32,973] INFO:  Iter 22/35 - Loss: 0.367 (delta=-0.019725)
[2026-04-28 00:22:34,488] INFO:  Iter 23/35 - Loss: 0.347 (delta=-0.020568)
[2026-04-28 00:22:36,028] INFO:  Iter 24/35 - Loss: 0.327 (delta=-0.019825)
[2026-04-28 00:22:37,503] INFO:  Iter 25/35 - Loss: 0.307 (delta=-0.019798)
[2026-04-28 00:22:38,980] INFO:  Iter 26/35 - Loss: 0.287 (delta=-0.020391)
[2026-04-28 00:22:40,459] INFO:  Iter 27/35 - Loss: 0.266 (delta=-0.020393)
[2026-04-28 00:22:41,981] INFO:  Iter 28/35 - Loss: 0.246 (delta=-0.020047)
[2026-04-28 00:22:43,467] INFO:  Iter 29/35 - Loss: 0.225 (delta=-0.021127)
[2026-04-28 00:22:44,953] INFO:  Iter 30/35 - Loss: 0.206 (delta=-0.019606)
[2026-04-28 00:22:46,476] INFO:  Iter 31/35 - Loss: 0.185 (delta=-0.020424)
[2026-04-28 00:22:47,974] INFO:  Iter 32/35 - Loss: 0.164 (delta=-0.020803)
[2026-04-28 00:22:49,484] INFO:  Iter 33/35 - Loss: 0.145 (delta=-0.019872)
[2026-04-28 00:22:51,320] INFO:  Iter 34/35 - Loss: 0.124 (delta=-0.020293)
[2026-04-28 00:22:52,948] INFO:  Iter 35/35 - Loss: 0.102 (delta=-0.022034)

  cell_2_2: 15000 pts, 35 iters, final loss = 0.1023

[2026-04-28 00:22:54,473] INFO:  Iter 1/35 - Loss: 0.767 (delta=inf)
[2026-04-28 00:22:56,019] INFO:  Iter 2/35 - Loss: 0.749 (delta=-0.018231)
[2026-04-28 00:22:57,538] INFO:  Iter 3/35 - Loss: 0.731 (delta=-0.018124)
[2026-04-28 00:22:59,052] INFO:  Iter 4/35 - Loss: 0.712 (delta=-0.018583)
[2026-04-28 00:23:00,577] INFO:  Iter 5/35 - Loss: 0.694 (delta=-0.018501)
[2026-04-28 00:23:02,091] INFO:  Iter 6/35 - Loss: 0.675 (delta=-0.018466)
[2026-04-28 00:23:04,624] INFO:  Iter 7/35 - Loss: 0.656 (delta=-0.018705)
[2026-04-28 00:23:06,136] INFO:  Iter 8/35 - Loss: 0.637 (delta=-0.019077)
[2026-04-28 00:23:07,631] INFO:  Iter 9/35 - Loss: 0.618 (delta=-0.018987)
[2026-04-28 00:23:09,127] INFO:  Iter 10/35 - Loss: 0.599 (delta=-0.019037)
[2026-04-28 00:23:10,608] INFO:  Iter 11/35 - Loss: 0.580 (delta=-0.019303)
[2026-04-28 00:23:12,101] INFO:  Iter 12/35 - Loss: 0.561 (delta=-0.019250)
[2026-04-28 00:23:13,596] INFO:  Iter 13/35 - Loss: 0.541 (delta=-0.019285)
[2026-04-28 00:23:15,211] INFO:  Iter 14/35 - Loss: 0.522 (delta=-0.019669)
[2026-04-28 00:23:16,724] INFO:  Iter 15/35 - Loss: 0.502 (delta=-0.019476)
[2026-04-28 00:23:18,230] INFO:  Iter 16/35 - Loss: 0.483 (delta=-0.019657)
[2026-04-28 00:23:19,755] INFO:  Iter 17/35 - Loss: 0.462 (delta=-0.020292)
[2026-04-28 00:23:21,287] INFO:  Iter 18/35 - Loss: 0.443 (delta=-0.019138)
[2026-04-28 00:23:22,976] INFO:  Iter 19/35 - Loss: 0.423 (delta=-0.020542)
[2026-04-28 00:23:25,624] INFO:  Iter 20/35 - Loss: 0.403 (delta=-0.020068)
[2026-04-28 00:23:27,219] INFO:  Iter 21/35 - Loss: 0.382 (delta=-0.020496)
[2026-04-28 00:23:28,705] INFO:  Iter 22/35 - Loss: 0.363 (delta=-0.019635)
[2026-04-28 00:23:30,189] INFO:  Iter 23/35 - Loss: 0.342 (delta=-0.020717)
[2026-04-28 00:23:31,833] INFO:  Iter 24/35 - Loss: 0.322 (delta=-0.020022)
[2026-04-28 00:23:33,368] INFO:  Iter 25/35 - Loss: 0.300 (delta=-0.021274)
[2026-04-28 00:23:34,891] INFO:  Iter 26/35 - Loss: 0.280 (delta=-0.020099)
[2026-04-28 00:23:36,504] INFO:  Iter 27/35 - Loss: 0.260 (delta=-0.020600)
[2026-04-28 00:23:39,177] INFO:  Iter 28/35 - Loss: 0.239 (delta=-0.020656)
[2026-04-28 00:23:40,688] INFO:  Iter 29/35 - Loss: 0.218 (delta=-0.021269)
[2026-04-28 00:23:42,173] INFO:  Iter 30/35 - Loss: 0.196 (delta=-0.021910)
[2026-04-28 00:23:43,657] INFO:  Iter 31/35 - Loss: 0.176 (delta=-0.019855)
[2026-04-28 00:23:45,128] INFO:  Iter 32/35 - Loss: 0.156 (delta=-0.020215)
[2026-04-28 00:23:47,360] INFO:  Iter 33/35 - Loss: 0.132 (delta=-0.023648)
[2026-04-28 00:23:48,993] INFO:  Iter 34/35 - Loss: 0.111 (delta=-0.021484)
[2026-04-28 00:23:50,514] INFO:  Iter 35/35 - Loss: 0.086 (delta=-0.024942)

  cell_2_3: 15000 pts, 35 iters, final loss = 0.0858

[2026-04-28 00:23:52,055] INFO:  Iter 1/35 - Loss: 0.778 (delta=inf)
[2026-04-28 00:23:53,618] INFO:  Iter 2/35 - Loss: 0.761 (delta=-0.017722)
[2026-04-28 00:23:55,152] INFO:  Iter 3/35 - Loss: 0.743 (delta=-0.017513)
[2026-04-28 00:23:56,719] INFO:  Iter 4/35 - Loss: 0.726 (delta=-0.017488)
[2026-04-28 00:23:58,285] INFO:  Iter 5/35 - Loss: 0.708 (delta=-0.018001)
[2026-04-28 00:23:59,880] INFO:  Iter 6/35 - Loss: 0.690 (delta=-0.017867)
[2026-04-28 00:24:02,640] INFO:  Iter 7/35 - Loss: 0.672 (delta=-0.018114)
[2026-04-28 00:24:04,440] INFO:  Iter 8/35 - Loss: 0.654 (delta=-0.017967)
[2026-04-28 00:24:06,010] INFO:  Iter 9/35 - Loss: 0.636 (delta=-0.018115)
[2026-04-28 00:24:08,573] INFO:  Iter 10/35 - Loss: 0.617 (delta=-0.018182)
[2026-04-28 00:24:10,122] INFO:  Iter 11/35 - Loss: 0.599 (delta=-0.018900)
[2026-04-28 00:24:11,847] INFO:  Iter 12/35 - Loss: 0.580 (delta=-0.018311)
[2026-04-28 00:24:13,461] INFO:  Iter 13/35 - Loss: 0.561 (delta=-0.018755)
[2026-04-28 00:24:15,015] INFO:  Iter 14/35 - Loss: 0.543 (delta=-0.018609)
[2026-04-28 00:24:17,659] INFO:  Iter 15/35 - Loss: 0.524 (delta=-0.018796)
[2026-04-28 00:24:19,353] INFO:  Iter 16/35 - Loss: 0.505 (delta=-0.018683)
[2026-04-28 00:24:21,064] INFO:  Iter 17/35 - Loss: 0.486 (delta=-0.019313)
[2026-04-28 00:24:22,651] INFO:  Iter 18/35 - Loss: 0.468 (delta=-0.018486)
[2026-04-28 00:24:24,203] INFO:  Iter 19/35 - Loss: 0.449 (delta=-0.018971)
[2026-04-28 00:24:25,715] INFO:  Iter 20/35 - Loss: 0.430 (delta=-0.019090)
[2026-04-28 00:24:27,261] INFO:  Iter 21/35 - Loss: 0.411 (delta=-0.018830)
[2026-04-28 00:24:28,788] INFO:  Iter 22/35 - Loss: 0.391 (delta=-0.019518)
[2026-04-28 00:24:30,328] INFO:  Iter 23/35 - Loss: 0.373 (delta=-0.018514)
[2026-04-28 00:24:32,936] INFO:  Iter 24/35 - Loss: 0.354 (delta=-0.018858)
[2026-04-28 00:24:34,655] INFO:  Iter 25/35 - Loss: 0.334 (delta=-0.019440)
[2026-04-28 00:24:37,394] INFO:  Iter 26/35 - Loss: 0.316 (delta=-0.018674)
[2026-04-28 00:24:39,181] INFO:  Iter 27/35 - Loss: 0.297 (delta=-0.018923)
[2026-04-28 00:24:40,703] INFO:  Iter 28/35 - Loss: 0.279 (delta=-0.018014)
[2026-04-28 00:24:42,241] INFO:  Iter 29/35 - Loss: 0.260 (delta=-0.018330)
[2026-04-28 00:24:44,973] INFO:  Iter 30/35 - Loss: 0.241 (delta=-0.019264)
[2026-04-28 00:24:46,659] INFO:  Iter 31/35 - Loss: 0.223 (delta=-0.017658)
[2026-04-28 00:24:48,165] INFO:  Iter 32/35 - Loss: 0.204 (delta=-0.019759)
[2026-04-28 00:24:49,673] INFO:  Iter 33/35 - Loss: 0.186 (delta=-0.017903)
[2026-04-28 00:24:51,204] INFO:  Iter 34/35 - Loss: 0.167 (delta=-0.018846)
[2026-04-28 00:24:52,709] INFO:  Iter 35/35 - Loss: 0.151 (delta=-0.015910)

  cell_3_0: 15000 pts, 35 iters, final loss = 0.1511

[2026-04-28 00:24:54,271] INFO:  Iter 1/35 - Loss: 0.780 (delta=inf)
[2026-04-28 00:24:55,820] INFO:  Iter 2/35 - Loss: 0.762 (delta=-0.017502)
[2026-04-28 00:24:58,453] INFO:  Iter 3/35 - Loss: 0.745 (delta=-0.017462)
[2026-04-28 00:24:59,979] INFO:  Iter 4/35 - Loss: 0.727 (delta=-0.017550)
[2026-04-28 00:25:01,472] INFO:  Iter 5/35 - Loss: 0.709 (delta=-0.017677)
[2026-04-28 00:25:02,974] INFO:  Iter 6/35 - Loss: 0.691 (delta=-0.017958)
[2026-04-28 00:25:04,505] INFO:  Iter 7/35 - Loss: 0.674 (delta=-0.017807)
[2026-04-28 00:25:06,062] INFO:  Iter 8/35 - Loss: 0.655 (delta=-0.018151)
[2026-04-28 00:25:07,620] INFO:  Iter 9/35 - Loss: 0.637 (delta=-0.018046)
[2026-04-28 00:25:09,152] INFO:  Iter 10/35 - Loss: 0.619 (delta=-0.018674)
[2026-04-28 00:25:11,803] INFO:  Iter 11/35 - Loss: 0.600 (delta=-0.018291)
[2026-04-28 00:25:13,511] INFO:  Iter 12/35 - Loss: 0.582 (delta=-0.018676)
[2026-04-28 00:25:16,373] INFO:  Iter 13/35 - Loss: 0.563 (delta=-0.018434)
[2026-04-28 00:25:18,158] INFO:  Iter 14/35 - Loss: 0.545 (delta=-0.018861)
[2026-04-28 00:25:20,956] INFO:  Iter 15/35 - Loss: 0.526 (delta=-0.018841)
[2026-04-28 00:25:22,874] INFO:  Iter 16/35 - Loss: 0.507 (delta=-0.018614)
[2026-04-28 00:25:25,473] INFO:  Iter 17/35 - Loss: 0.488 (delta=-0.019224)
[2026-04-28 00:25:27,198] INFO:  Iter 18/35 - Loss: 0.469 (delta=-0.018524)
[2026-04-28 00:25:28,796] INFO:  Iter 19/35 - Loss: 0.450 (delta=-0.019309)
[2026-04-28 00:25:31,450] INFO:  Iter 20/35 - Loss: 0.431 (delta=-0.018983)
[2026-04-28 00:25:33,094] INFO:  Iter 21/35 - Loss: 0.412 (delta=-0.018756)
[2026-04-28 00:25:34,612] INFO:  Iter 22/35 - Loss: 0.394 (delta=-0.018593)
[2026-04-28 00:25:36,497] INFO:  Iter 23/35 - Loss: 0.374 (delta=-0.019287)
[2026-04-28 00:25:38,080] INFO:  Iter 24/35 - Loss: 0.356 (delta=-0.018579)
[2026-04-28 00:25:39,588] INFO:  Iter 25/35 - Loss: 0.337 (delta=-0.019105)
[2026-04-28 00:25:41,134] INFO:  Iter 26/35 - Loss: 0.319 (delta=-0.018154)
[2026-04-28 00:25:42,694] INFO:  Iter 27/35 - Loss: 0.300 (delta=-0.018716)
[2026-04-28 00:25:44,742] INFO:  Iter 28/35 - Loss: 0.281 (delta=-0.018548)
[2026-04-28 00:25:46,284] INFO:  Iter 29/35 - Loss: 0.263 (delta=-0.018385)
[2026-04-28 00:25:47,880] INFO:  Iter 30/35 - Loss: 0.245 (delta=-0.018049)
[2026-04-28 00:25:49,413] INFO:  Iter 31/35 - Loss: 0.227 (delta=-0.018148)
[2026-04-28 00:25:51,023] INFO:  Iter 32/35 - Loss: 0.208 (delta=-0.018831)
[2026-04-28 00:25:52,545] INFO:  Iter 33/35 - Loss: 0.189 (delta=-0.018975)
[2026-04-28 00:25:54,164] INFO:  Iter 34/35 - Loss: 0.171 (delta=-0.017651)
[2026-04-28 00:25:55,752] INFO:  Iter 35/35 - Loss: 0.155 (delta=-0.015981)

  cell_3_1: 15000 pts, 35 iters, final loss = 0.1553

[2026-04-28 00:25:57,353] INFO:  Iter 1/35 - Loss: 0.774 (delta=inf)
[2026-04-28 00:25:58,910] INFO:  Iter 2/35 - Loss: 0.757 (delta=-0.017719)
[2026-04-28 00:26:00,500] INFO:  Iter 3/35 - Loss: 0.739 (delta=-0.017505)
[2026-04-28 00:26:02,968] INFO:  Iter 4/35 - Loss: 0.721 (delta=-0.017903)
[2026-04-28 00:26:04,577] INFO:  Iter 5/35 - Loss: 0.704 (delta=-0.017579)
[2026-04-28 00:26:06,403] INFO:  Iter 6/35 - Loss: 0.686 (delta=-0.018081)
[2026-04-28 00:26:08,071] INFO:  Iter 7/35 - Loss: 0.668 (delta=-0.018041)
[2026-04-28 00:26:10,820] INFO:  Iter 8/35 - Loss: 0.649 (delta=-0.018166)
[2026-04-28 00:26:12,418] INFO:  Iter 9/35 - Loss: 0.631 (delta=-0.018326)
[2026-04-28 00:26:13,930] INFO:  Iter 10/35 - Loss: 0.613 (delta=-0.018460)
[2026-04-28 00:26:15,495] INFO:  Iter 11/35 - Loss: 0.594 (delta=-0.018456)
[2026-04-28 00:26:17,240] INFO:  Iter 12/35 - Loss: 0.575 (delta=-0.018775)
[2026-04-28 00:26:18,782] INFO:  Iter 13/35 - Loss: 0.557 (delta=-0.018806)
[2026-04-28 00:26:20,301] INFO:  Iter 14/35 - Loss: 0.538 (delta=-0.018669)
[2026-04-28 00:26:21,814] INFO:  Iter 15/35 - Loss: 0.519 (delta=-0.018979)
[2026-04-28 00:26:23,350] INFO:  Iter 16/35 - Loss: 0.500 (delta=-0.019136)
[2026-04-28 00:26:24,996] INFO:  Iter 17/35 - Loss: 0.481 (delta=-0.018856)
[2026-04-28 00:26:26,549] INFO:  Iter 18/35 - Loss: 0.462 (delta=-0.019269)
[2026-04-28 00:26:28,161] INFO:  Iter 19/35 - Loss: 0.443 (delta=-0.019129)
[2026-04-28 00:26:29,813] INFO:  Iter 20/35 - Loss: 0.424 (delta=-0.019033)
[2026-04-28 00:26:32,589] INFO:  Iter 21/35 - Loss: 0.404 (delta=-0.019111)
[2026-04-28 00:26:34,383] INFO:  Iter 22/35 - Loss: 0.385 (delta=-0.019570)
[2026-04-28 00:26:36,212] INFO:  Iter 23/35 - Loss: 0.366 (delta=-0.018760)
[2026-04-28 00:26:37,822] INFO:  Iter 24/35 - Loss: 0.347 (delta=-0.019363)
[2026-04-28 00:26:39,451] INFO:  Iter 25/35 - Loss: 0.327 (delta=-0.019463)
[2026-04-28 00:26:41,006] INFO:  Iter 26/35 - Loss: 0.309 (delta=-0.018436)
[2026-04-28 00:26:42,556] INFO:  Iter 27/35 - Loss: 0.290 (delta=-0.019313)
[2026-04-28 00:26:44,101] INFO:  Iter 28/35 - Loss: 0.271 (delta=-0.018010)
[2026-04-28 00:26:45,674] INFO:  Iter 29/35 - Loss: 0.252 (delta=-0.019951)
[2026-04-28 00:26:47,220] INFO:  Iter 30/35 - Loss: 0.233 (delta=-0.018975)
[2026-04-28 00:26:48,771] INFO:  Iter 31/35 - Loss: 0.213 (delta=-0.019106)
[2026-04-28 00:26:50,342] INFO:  Iter 32/35 - Loss: 0.195 (delta=-0.017994)
[2026-04-28 00:26:51,876] INFO:  Iter 33/35 - Loss: 0.176 (delta=-0.019521)
[2026-04-28 00:26:53,405] INFO:  Iter 34/35 - Loss: 0.158 (delta=-0.018179)
[2026-04-28 00:26:55,006] INFO:  Iter 35/35 - Loss: 0.141 (delta=-0.017027)

  cell_3_2: 15000 pts, 35 iters, final loss = 0.1407

[2026-04-28 00:26:56,624] INFO:  Iter 1/35 - Loss: 0.765 (delta=inf)
[2026-04-28 00:26:59,084] INFO:  Iter 2/35 - Loss: 0.747 (delta=-0.018430)
[2026-04-28 00:27:00,665] INFO:  Iter 3/35 - Loss: 0.729 (delta=-0.018251)
[2026-04-28 00:27:02,290] INFO:  Iter 4/35 - Loss: 0.710 (delta=-0.018589)
[2026-04-28 00:27:04,103] INFO:  Iter 5/35 - Loss: 0.691 (delta=-0.018618)
[2026-04-28 00:27:05,742] INFO:  Iter 6/35 - Loss: 0.672 (delta=-0.019048)
[2026-04-28 00:27:07,390] INFO:  Iter 7/35 - Loss: 0.653 (delta=-0.018877)
[2026-04-28 00:27:08,968] INFO:  Iter 8/35 - Loss: 0.634 (delta=-0.019437)
[2026-04-28 00:27:10,500] INFO:  Iter 9/35 - Loss: 0.615 (delta=-0.019165)
[2026-04-28 00:27:12,440] INFO:  Iter 10/35 - Loss: 0.596 (delta=-0.019299)
[2026-04-28 00:27:14,034] INFO:  Iter 11/35 - Loss: 0.576 (delta=-0.019374)
[2026-04-28 00:27:15,552] INFO:  Iter 12/35 - Loss: 0.557 (delta=-0.019447)
[2026-04-28 00:27:17,093] INFO:  Iter 13/35 - Loss: 0.537 (delta=-0.019275)
[2026-04-28 00:27:18,721] INFO:  Iter 14/35 - Loss: 0.517 (delta=-0.020002)
[2026-04-28 00:27:20,313] INFO:  Iter 15/35 - Loss: 0.498 (delta=-0.019729)
[2026-04-28 00:27:21,877] INFO:  Iter 16/35 - Loss: 0.478 (delta=-0.019976)
[2026-04-28 00:27:23,408] INFO:  Iter 17/35 - Loss: 0.458 (delta=-0.020139)
[2026-04-28 00:27:25,572] INFO:  Iter 18/35 - Loss: 0.438 (delta=-0.019963)
[2026-04-28 00:27:27,121] INFO:  Iter 19/35 - Loss: 0.417 (delta=-0.020570)
[2026-04-28 00:27:28,700] INFO:  Iter 20/35 - Loss: 0.397 (delta=-0.019807)
[2026-04-28 00:27:30,932] INFO:  Iter 21/35 - Loss: 0.376 (delta=-0.020948)
[2026-04-28 00:27:32,870] INFO:  Iter 22/35 - Loss: 0.356 (delta=-0.020225)
[2026-04-28 00:27:34,450] INFO:  Iter 23/35 - Loss: 0.336 (delta=-0.020254)
[2026-04-28 00:27:36,131] INFO:  Iter 24/35 - Loss: 0.315 (delta=-0.021251)
[2026-04-28 00:27:37,703] INFO:  Iter 25/35 - Loss: 0.294 (delta=-0.020445)
[2026-04-28 00:27:39,230] INFO:  Iter 26/35 - Loss: 0.273 (delta=-0.020965)
[2026-04-28 00:27:40,794] INFO:  Iter 27/35 - Loss: 0.252 (delta=-0.021204)
[2026-04-28 00:27:42,317] INFO:  Iter 28/35 - Loss: 0.231 (delta=-0.020486)
[2026-04-28 00:27:43,879] INFO:  Iter 29/35 - Loss: 0.210 (delta=-0.021674)
[2026-04-28 00:27:45,407] INFO:  Iter 30/35 - Loss: 0.190 (delta=-0.020074)
[2026-04-28 00:27:47,845] INFO:  Iter 31/35 - Loss: 0.167 (delta=-0.022721)
[2026-04-28 00:27:49,434] INFO:  Iter 32/35 - Loss: 0.147 (delta=-0.019827)
[2026-04-28 00:27:50,986] INFO:  Iter 33/35 - Loss: 0.127 (delta=-0.020009)
[2026-04-28 00:27:52,522] INFO:  Iter 34/35 - Loss: 0.106 (delta=-0.021466)
[2026-04-28 00:27:54,052] INFO:  Iter 35/35 - Loss: 0.084 (delta=-0.021886)

  cell_3_3: 15000 pts, 35 iters, final loss = 0.0838

[2026-04-28 00:27:56,552] INFO:  Iter 1/35 - Loss: 0.776 (delta=inf)
[2026-04-28 00:27:58,196] INFO:  Iter 2/35 - Loss: 0.758 (delta=-0.017733)
[2026-04-28 00:27:59,769] INFO:  Iter 3/35 - Loss: 0.740 (delta=-0.017735)
[2026-04-28 00:28:01,348] INFO:  Iter 4/35 - Loss: 0.722 (delta=-0.017936)
[2026-04-28 00:28:02,911] INFO:  Iter 5/35 - Loss: 0.704 (delta=-0.017958)
[2026-04-28 00:28:04,572] INFO:  Iter 6/35 - Loss: 0.686 (delta=-0.018057)
[2026-04-28 00:28:06,097] INFO:  Iter 7/35 - Loss: 0.668 (delta=-0.018598)
[2026-04-28 00:28:08,012] INFO:  Iter 8/35 - Loss: 0.649 (delta=-0.018059)
[2026-04-28 00:28:09,680] INFO:  Iter 9/35 - Loss: 0.631 (delta=-0.018701)
[2026-04-28 00:28:11,222] INFO:  Iter 10/35 - Loss: 0.612 (delta=-0.018620)
[2026-04-28 00:28:12,769] INFO:  Iter 11/35 - Loss: 0.594 (delta=-0.018358)
[2026-04-28 00:28:14,298] INFO:  Iter 12/35 - Loss: 0.575 (delta=-0.018629)
[2026-04-28 00:28:15,863] INFO:  Iter 13/35 - Loss: 0.556 (delta=-0.019037)
[2026-04-28 00:28:17,382] INFO:  Iter 14/35 - Loss: 0.537 (delta=-0.018976)
[2026-04-28 00:28:18,953] INFO:  Iter 15/35 - Loss: 0.518 (delta=-0.018792)
[2026-04-28 00:28:20,823] INFO:  Iter 16/35 - Loss: 0.499 (delta=-0.019309)
[2026-04-28 00:28:22,398] INFO:  Iter 17/35 - Loss: 0.480 (delta=-0.018905)
[2026-04-28 00:28:23,921] INFO:  Iter 18/35 - Loss: 0.461 (delta=-0.019509)
[2026-04-28 00:28:25,453] INFO:  Iter 19/35 - Loss: 0.442 (delta=-0.018744)
[2026-04-28 00:28:27,051] INFO:  Iter 20/35 - Loss: 0.423 (delta=-0.019234)
[2026-04-28 00:28:28,967] INFO:  Iter 21/35 - Loss: 0.404 (delta=-0.018749)
[2026-04-28 00:28:31,736] INFO:  Iter 22/35 - Loss: 0.385 (delta=-0.019049)
[2026-04-28 00:28:33,363] INFO:  Iter 23/35 - Loss: 0.365 (delta=-0.019940)
[2026-04-28 00:28:34,895] INFO:  Iter 24/35 - Loss: 0.346 (delta=-0.019239)
[2026-04-28 00:28:36,510] INFO:  Iter 25/35 - Loss: 0.327 (delta=-0.019040)
[2026-04-28 00:28:38,087] INFO:  Iter 26/35 - Loss: 0.307 (delta=-0.019354)
[2026-04-28 00:28:39,623] INFO:  Iter 27/35 - Loss: 0.289 (delta=-0.018696)
[2026-04-28 00:28:41,230] INFO:  Iter 28/35 - Loss: 0.269 (delta=-0.019156)
[2026-04-28 00:28:42,777] INFO:  Iter 29/35 - Loss: 0.250 (delta=-0.018987)
[2026-04-28 00:28:44,447] INFO:  Iter 30/35 - Loss: 0.232 (delta=-0.018937)
[2026-04-28 00:28:45,986] INFO:  Iter 31/35 - Loss: 0.213 (delta=-0.018477)
[2026-04-28 00:28:47,837] INFO:  Iter 32/35 - Loss: 0.194 (delta=-0.018878)
[2026-04-28 00:28:49,405] INFO:  Iter 33/35 - Loss: 0.175 (delta=-0.019413)
[2026-04-28 00:28:50,997] INFO:  Iter 34/35 - Loss: 0.157 (delta=-0.017382)
[2026-04-28 00:28:52,530] INFO:  Iter 35/35 - Loss: 0.139 (delta=-0.018383)

  cell_4_0: 15000 pts, 35 iters, final loss = 0.1390

[2026-04-28 00:28:54,118] INFO:  Iter 1/35 - Loss: 0.764 (delta=inf)
[2026-04-28 00:28:55,682] INFO:  Iter 2/35 - Loss: 0.747 (delta=-0.017795)
[2026-04-28 00:28:57,585] INFO:  Iter 3/35 - Loss: 0.729 (delta=-0.017885)
[2026-04-28 00:28:59,207] INFO:  Iter 4/35 - Loss: 0.711 (delta=-0.018226)
[2026-04-28 00:29:01,666] INFO:  Iter 5/35 - Loss: 0.692 (delta=-0.018317)
[2026-04-28 00:29:03,236] INFO:  Iter 6/35 - Loss: 0.674 (delta=-0.018364)
[2026-04-28 00:29:04,781] INFO:  Iter 7/35 - Loss: 0.655 (delta=-0.018752)
[2026-04-28 00:29:06,392] INFO:  Iter 8/35 - Loss: 0.636 (delta=-0.018679)
[2026-04-28 00:29:07,929] INFO:  Iter 9/35 - Loss: 0.618 (delta=-0.018860)
[2026-04-28 00:29:10,100] INFO:  Iter 10/35 - Loss: 0.598 (delta=-0.019129)
[2026-04-28 00:29:11,682] INFO:  Iter 11/35 - Loss: 0.579 (delta=-0.019271)
[2026-04-28 00:29:13,200] INFO:  Iter 12/35 - Loss: 0.560 (delta=-0.019299)
[2026-04-28 00:29:14,753] INFO:  Iter 13/35 - Loss: 0.541 (delta=-0.019275)
[2026-04-28 00:29:16,261] INFO:  Iter 14/35 - Loss: 0.521 (delta=-0.019437)
[2026-04-28 00:29:18,142] INFO:  Iter 15/35 - Loss: 0.502 (delta=-0.019581)
[2026-04-28 00:29:19,716] INFO:  Iter 16/35 - Loss: 0.482 (delta=-0.019287)
[2026-04-28 00:29:21,287] INFO:  Iter 17/35 - Loss: 0.463 (delta=-0.019772)
[2026-04-28 00:29:22,809] INFO:  Iter 18/35 - Loss: 0.442 (delta=-0.020195)
[2026-04-28 00:29:24,319] INFO:  Iter 19/35 - Loss: 0.422 (delta=-0.020014)
[2026-04-28 00:29:25,831] INFO:  Iter 20/35 - Loss: 0.403 (delta=-0.019741)
[2026-04-28 00:29:27,983] INFO:  Iter 21/35 - Loss: 0.382 (delta=-0.020317)
[2026-04-28 00:29:29,625] INFO:  Iter 22/35 - Loss: 0.362 (delta=-0.019790)
[2026-04-28 00:29:32,156] INFO:  Iter 23/35 - Loss: 0.342 (delta=-0.020009)
[2026-04-28 00:29:33,748] INFO:  Iter 24/35 - Loss: 0.322 (delta=-0.020506)
[2026-04-28 00:29:35,330] INFO:  Iter 25/35 - Loss: 0.302 (delta=-0.020040)
[2026-04-28 00:29:36,903] INFO:  Iter 26/35 - Loss: 0.281 (delta=-0.020833)
[2026-04-28 00:29:38,428] INFO:  Iter 27/35 - Loss: 0.261 (delta=-0.020379)
[2026-04-28 00:29:40,712] INFO:  Iter 28/35 - Loss: 0.241 (delta=-0.020141)
[2026-04-28 00:29:42,890] INFO:  Iter 29/35 - Loss: 0.220 (delta=-0.020105)
[2026-04-28 00:29:45,091] INFO:  Iter 30/35 - Loss: 0.201 (delta=-0.019915)
[2026-04-28 00:29:46,680] INFO:  Iter 31/35 - Loss: 0.180 (delta=-0.020478)
[2026-04-28 00:29:48,180] INFO:  Iter 32/35 - Loss: 0.160 (delta=-0.019936)
[2026-04-28 00:29:49,682] INFO:  Iter 33/35 - Loss: 0.139 (delta=-0.020687)
[2026-04-28 00:29:51,229] INFO:  Iter 34/35 - Loss: 0.119 (delta=-0.020113)
[2026-04-28 00:29:52,739] INFO:  Iter 35/35 - Loss: 0.099 (delta=-0.019903)

  cell_4_1: 15000 pts, 35 iters, final loss = 0.0994

[2026-04-28 00:29:54,322] INFO:  Iter 1/35 - Loss: 0.773 (delta=inf)
[2026-04-28 00:29:55,982] INFO:  Iter 2/35 - Loss: 0.756 (delta=-0.017517)
[2026-04-28 00:29:58,512] INFO:  Iter 3/35 - Loss: 0.738 (delta=-0.017996)
[2026-04-28 00:30:00,083] INFO:  Iter 4/35 - Loss: 0.720 (delta=-0.017538)
[2026-04-28 00:30:01,667] INFO:  Iter 5/35 - Loss: 0.702 (delta=-0.018336)
[2026-04-28 00:30:03,289] INFO:  Iter 6/35 - Loss: 0.684 (delta=-0.018109)
[2026-04-28 00:30:04,854] INFO:  Iter 7/35 - Loss: 0.666 (delta=-0.018326)
[2026-04-28 00:30:06,367] INFO:  Iter 8/35 - Loss: 0.647 (delta=-0.018402)
[2026-04-28 00:30:08,486] INFO:  Iter 9/35 - Loss: 0.629 (delta=-0.018438)
[2026-04-28 00:30:10,075] INFO:  Iter 10/35 - Loss: 0.610 (delta=-0.018479)
[2026-04-28 00:30:11,602] INFO:  Iter 11/35 - Loss: 0.592 (delta=-0.018728)
[2026-04-28 00:30:13,204] INFO:  Iter 12/35 - Loss: 0.573 (delta=-0.018507)
[2026-04-28 00:30:15,085] INFO:  Iter 13/35 - Loss: 0.554 (delta=-0.018985)
[2026-04-28 00:30:16,648] INFO:  Iter 14/35 - Loss: 0.535 (delta=-0.019071)
[2026-04-28 00:30:18,222] INFO:  Iter 15/35 - Loss: 0.516 (delta=-0.018878)
[2026-04-28 00:30:19,752] INFO:  Iter 16/35 - Loss: 0.497 (delta=-0.018877)
[2026-04-28 00:30:21,285] INFO:  Iter 17/35 - Loss: 0.478 (delta=-0.019694)
[2026-04-28 00:30:23,154] INFO:  Iter 18/35 - Loss: 0.458 (delta=-0.019164)
[2026-04-28 00:30:24,790] INFO:  Iter 19/35 - Loss: 0.439 (delta=-0.018972)
[2026-04-28 00:30:26,377] INFO:  Iter 20/35 - Loss: 0.420 (delta=-0.019107)
[2026-04-28 00:30:28,877] INFO:  Iter 21/35 - Loss: 0.401 (delta=-0.019156)
[2026-04-28 00:30:30,461] INFO:  Iter 22/35 - Loss: 0.381 (delta=-0.019734)
[2026-04-28 00:30:32,704] INFO:  Iter 23/35 - Loss: 0.362 (delta=-0.019565)
[2026-04-28 00:30:34,328] INFO:  Iter 24/35 - Loss: 0.342 (delta=-0.019807)
[2026-04-28 00:30:36,894] INFO:  Iter 25/35 - Loss: 0.323 (delta=-0.019466)
[2026-04-28 00:30:38,451] INFO:  Iter 26/35 - Loss: 0.303 (delta=-0.019595)
[2026-04-28 00:30:39,960] INFO:  Iter 27/35 - Loss: 0.283 (delta=-0.019591)
[2026-04-28 00:30:41,467] INFO:  Iter 28/35 - Loss: 0.264 (delta=-0.019513)
[2026-04-28 00:30:42,969] INFO:  Iter 29/35 - Loss: 0.245 (delta=-0.018598)
[2026-04-28 00:30:44,496] INFO:  Iter 30/35 - Loss: 0.225 (delta=-0.020376)
[2026-04-28 00:30:46,089] INFO:  Iter 31/35 - Loss: 0.204 (delta=-0.020653)
[2026-04-28 00:30:47,622] INFO:  Iter 32/35 - Loss: 0.186 (delta=-0.017818)
[2026-04-28 00:30:49,171] INFO:  Iter 33/35 - Loss: 0.167 (delta=-0.019041)
[2026-04-28 00:30:50,686] INFO:  Iter 34/35 - Loss: 0.149 (delta=-0.018689)
[2026-04-28 00:30:52,211] INFO:  Iter 35/35 - Loss: 0.128 (delta=-0.020988)

  cell_4_2: 15000 pts, 35 iters, final loss = 0.1277

[2026-04-28 00:30:53,800] INFO:  Iter 1/35 - Loss: 0.777 (delta=inf)
[2026-04-28 00:30:55,317] INFO:  Iter 2/35 - Loss: 0.759 (delta=-0.017774)
[2026-04-28 00:30:56,843] INFO:  Iter 3/35 - Loss: 0.741 (delta=-0.017970)
[2026-04-28 00:30:59,070] INFO:  Iter 4/35 - Loss: 0.724 (delta=-0.017692)
[2026-04-28 00:31:00,719] INFO:  Iter 5/35 - Loss: 0.705 (delta=-0.018351)
[2026-04-28 00:31:02,402] INFO:  Iter 6/35 - Loss: 0.687 (delta=-0.018092)
[2026-04-28 00:31:04,007] INFO:  Iter 7/35 - Loss: 0.669 (delta=-0.018172)
[2026-04-28 00:31:05,531] INFO:  Iter 8/35 - Loss: 0.651 (delta=-0.018059)
[2026-04-28 00:31:07,054] INFO:  Iter 9/35 - Loss: 0.632 (delta=-0.018666)
[2026-04-28 00:31:08,571] INFO:  Iter 10/35 - Loss: 0.614 (delta=-0.018295)
[2026-04-28 00:31:10,714] INFO:  Iter 11/35 - Loss: 0.595 (delta=-0.018630)
[2026-04-28 00:31:12,365] INFO:  Iter 12/35 - Loss: 0.577 (delta=-0.018524)
[2026-04-28 00:31:13,899] INFO:  Iter 13/35 - Loss: 0.558 (delta=-0.018987)
[2026-04-28 00:31:15,423] INFO:  Iter 14/35 - Loss: 0.539 (delta=-0.018699)
[2026-04-28 00:31:16,940] INFO:  Iter 15/35 - Loss: 0.520 (delta=-0.018917)
[2026-04-28 00:31:18,545] INFO:  Iter 16/35 - Loss: 0.501 (delta=-0.018973)
[2026-04-28 00:31:20,081] INFO:  Iter 17/35 - Loss: 0.483 (delta=-0.018640)
[2026-04-28 00:31:21,611] INFO:  Iter 18/35 - Loss: 0.463 (delta=-0.019305)
[2026-04-28 00:31:23,618] INFO:  Iter 19/35 - Loss: 0.444 (delta=-0.019093)
[2026-04-28 00:31:25,197] INFO:  Iter 20/35 - Loss: 0.425 (delta=-0.018948)
[2026-04-28 00:31:26,696] INFO:  Iter 21/35 - Loss: 0.407 (delta=-0.018602)
[2026-04-28 00:31:28,233] INFO:  Iter 22/35 - Loss: 0.387 (delta=-0.019667)
[2026-04-28 00:31:29,771] INFO:  Iter 23/35 - Loss: 0.368 (delta=-0.018722)
[2026-04-28 00:31:32,361] INFO:  Iter 24/35 - Loss: 0.349 (delta=-0.018986)
[2026-04-28 00:31:33,984] INFO:  Iter 25/35 - Loss: 0.330 (delta=-0.019249)
[2026-04-28 00:31:35,571] INFO:  Iter 26/35 - Loss: 0.311 (delta=-0.019129)
[2026-04-28 00:31:37,162] INFO:  Iter 27/35 - Loss: 0.292 (delta=-0.018630)
[2026-04-28 00:31:38,732] INFO:  Iter 28/35 - Loss: 0.273 (delta=-0.019348)
[2026-04-28 00:31:40,260] INFO:  Iter 29/35 - Loss: 0.254 (delta=-0.019303)
[2026-04-28 00:31:42,161] INFO:  Iter 30/35 - Loss: 0.235 (delta=-0.018519)
[2026-04-28 00:31:43,734] INFO:  Iter 31/35 - Loss: 0.217 (delta=-0.018130)
[2026-04-28 00:31:45,276] INFO:  Iter 32/35 - Loss: 0.199 (delta=-0.018193)
[2026-04-28 00:31:46,779] INFO:  Iter 33/35 - Loss: 0.180 (delta=-0.019175)
[2026-04-28 00:31:48,283] INFO:  Iter 34/35 - Loss: 0.163 (delta=-0.017042)
[2026-04-28 00:31:49,866] INFO:  Iter 35/35 - Loss: 0.144 (delta=-0.018246)

  cell_4_3: 15000 pts, 35 iters, final loss = 0.1444

[2026-04-28 00:31:51,458] INFO:  Iter 1/35 - Loss: 0.768 (delta=inf)
[2026-04-28 00:31:52,989] INFO:  Iter 2/35 - Loss: 0.750 (delta=-0.018306)
[2026-04-28 00:31:54,511] INFO:  Iter 3/35 - Loss: 0.731 (delta=-0.018642)
[2026-04-28 00:31:56,071] INFO:  Iter 4/35 - Loss: 0.713 (delta=-0.018365)
[2026-04-28 00:31:57,614] INFO:  Iter 5/35 - Loss: 0.695 (delta=-0.018328)
[2026-04-28 00:31:59,772] INFO:  Iter 6/35 - Loss: 0.676 (delta=-0.018744)
[2026-04-28 00:32:01,405] INFO:  Iter 7/35 - Loss: 0.657 (delta=-0.018762)
[2026-04-28 00:32:02,941] INFO:  Iter 8/35 - Loss: 0.638 (delta=-0.018851)
[2026-04-28 00:32:04,684] INFO:  Iter 9/35 - Loss: 0.620 (delta=-0.018646)
[2026-04-28 00:32:06,225] INFO:  Iter 10/35 - Loss: 0.600 (delta=-0.019168)
[2026-04-28 00:32:07,839] INFO:  Iter 11/35 - Loss: 0.582 (delta=-0.018840)
[2026-04-28 00:32:09,372] INFO:  Iter 12/35 - Loss: 0.562 (delta=-0.019312)
[2026-04-28 00:32:10,891] INFO:  Iter 13/35 - Loss: 0.543 (delta=-0.018852)
[2026-04-28 00:32:13,162] INFO:  Iter 14/35 - Loss: 0.524 (delta=-0.019557)
[2026-04-28 00:32:14,785] INFO:  Iter 15/35 - Loss: 0.505 (delta=-0.019222)
[2026-04-28 00:32:17,345] INFO:  Iter 16/35 - Loss: 0.485 (delta=-0.019427)
[2026-04-28 00:32:18,969] INFO:  Iter 17/35 - Loss: 0.466 (delta=-0.019245)
[2026-04-28 00:32:20,487] INFO:  Iter 18/35 - Loss: 0.446 (delta=-0.020355)
[2026-04-28 00:32:21,996] INFO:  Iter 19/35 - Loss: 0.426 (delta=-0.019573)
[2026-04-28 00:32:23,510] INFO:  Iter 20/35 - Loss: 0.406 (delta=-0.020224)
[2026-04-28 00:32:25,000] INFO:  Iter 21/35 - Loss: 0.386 (delta=-0.019457)
[2026-04-28 00:32:26,489] INFO:  Iter 22/35 - Loss: 0.366 (delta=-0.020710)
[2026-04-28 00:32:27,979] INFO:  Iter 23/35 - Loss: 0.345 (delta=-0.020364)
[2026-04-28 00:32:30,116] INFO:  Iter 24/35 - Loss: 0.325 (delta=-0.019937)
[2026-04-28 00:32:32,765] INFO:  Iter 25/35 - Loss: 0.306 (delta=-0.019731)
[2026-04-28 00:32:34,333] INFO:  Iter 26/35 - Loss: 0.285 (delta=-0.020916)
[2026-04-28 00:32:35,967] INFO:  Iter 27/35 - Loss: 0.265 (delta=-0.019901)
[2026-04-28 00:32:37,590] INFO:  Iter 28/35 - Loss: 0.244 (delta=-0.020325)
[2026-04-28 00:32:39,153] INFO:  Iter 29/35 - Loss: 0.224 (delta=-0.020470)
[2026-04-28 00:32:40,764] INFO:  Iter 30/35 - Loss: 0.204 (delta=-0.020156)
[2026-04-28 00:32:42,363] INFO:  Iter 31/35 - Loss: 0.184 (delta=-0.019636)
[2026-04-28 00:32:43,897] INFO:  Iter 32/35 - Loss: 0.163 (delta=-0.020923)
[2026-04-28 00:32:46,506] INFO:  Iter 33/35 - Loss: 0.144 (delta=-0.019680)
[2026-04-28 00:32:48,042] INFO:  Iter 34/35 - Loss: 0.124 (delta=-0.019165)
[2026-04-28 00:32:49,552] INFO:  Iter 35/35 - Loss: 0.104 (delta=-0.020413)

  cell_5_0: 15000 pts, 35 iters, final loss = 0.1040

[2026-04-28 00:32:51,211] INFO:  Iter 1/35 - Loss: 0.767 (delta=inf)
[2026-04-28 00:32:52,784] INFO:  Iter 2/35 - Loss: 0.748 (delta=-0.018563)
[2026-04-28 00:32:54,340] INFO:  Iter 3/35 - Loss: 0.729 (delta=-0.018578)
[2026-04-28 00:32:55,879] INFO:  Iter 4/35 - Loss: 0.711 (delta=-0.018751)
[2026-04-28 00:32:57,755] INFO:  Iter 5/35 - Loss: 0.692 (delta=-0.018732)
[2026-04-28 00:32:59,420] INFO:  Iter 6/35 - Loss: 0.673 (delta=-0.018626)
[2026-04-28 00:33:01,537] INFO:  Iter 7/35 - Loss: 0.655 (delta=-0.018867)
[2026-04-28 00:33:03,216] INFO:  Iter 8/35 - Loss: 0.636 (delta=-0.018983)
[2026-04-28 00:33:04,804] INFO:  Iter 9/35 - Loss: 0.617 (delta=-0.018687)
[2026-04-28 00:33:06,927] INFO:  Iter 10/35 - Loss: 0.598 (delta=-0.019241)
[2026-04-28 00:33:08,541] INFO:  Iter 11/35 - Loss: 0.578 (delta=-0.019359)
[2026-04-28 00:33:10,071] INFO:  Iter 12/35 - Loss: 0.559 (delta=-0.019033)
[2026-04-28 00:33:11,907] INFO:  Iter 13/35 - Loss: 0.540 (delta=-0.019234)
[2026-04-28 00:33:13,480] INFO:  Iter 14/35 - Loss: 0.521 (delta=-0.019291)
[2026-04-28 00:33:15,037] INFO:  Iter 15/35 - Loss: 0.501 (delta=-0.019389)
[2026-04-28 00:33:17,177] INFO:  Iter 16/35 - Loss: 0.481 (delta=-0.019900)
[2026-04-28 00:33:18,782] INFO:  Iter 17/35 - Loss: 0.461 (delta=-0.020072)
[2026-04-28 00:33:20,326] INFO:  Iter 18/35 - Loss: 0.441 (delta=-0.019946)
[2026-04-28 00:33:22,350] INFO:  Iter 19/35 - Loss: 0.421 (delta=-0.019900)
[2026-04-28 00:33:23,923] INFO:  Iter 20/35 - Loss: 0.401 (delta=-0.020483)
[2026-04-28 00:33:25,446] INFO:  Iter 21/35 - Loss: 0.381 (delta=-0.019961)
[2026-04-28 00:33:26,969] INFO:  Iter 22/35 - Loss: 0.361 (delta=-0.019583)
[2026-04-28 00:33:28,482] INFO:  Iter 23/35 - Loss: 0.341 (delta=-0.020612)
[2026-04-28 00:33:31,068] INFO:  Iter 24/35 - Loss: 0.320 (delta=-0.020423)
[2026-04-28 00:33:32,702] INFO:  Iter 25/35 - Loss: 0.300 (delta=-0.020651)
[2026-04-28 00:33:34,232] INFO:  Iter 26/35 - Loss: 0.279 (delta=-0.020698)
[2026-04-28 00:33:35,801] INFO:  Iter 27/35 - Loss: 0.259 (delta=-0.019979)
[2026-04-28 00:33:37,443] INFO:  Iter 28/35 - Loss: 0.238 (delta=-0.020769)
[2026-04-28 00:33:38,989] INFO:  Iter 29/35 - Loss: 0.218 (delta=-0.020409)
[2026-04-28 00:33:40,607] INFO:  Iter 30/35 - Loss: 0.197 (delta=-0.021116)
[2026-04-28 00:33:42,230] INFO:  Iter 31/35 - Loss: 0.177 (delta=-0.019652)
[2026-04-28 00:33:44,067] INFO:  Iter 32/35 - Loss: 0.156 (delta=-0.020935)
[2026-04-28 00:33:45,625] INFO:  Iter 33/35 - Loss: 0.136 (delta=-0.020533)
[2026-04-28 00:33:47,203] INFO:  Iter 34/35 - Loss: 0.116 (delta=-0.019908)
[2026-04-28 00:33:48,762] INFO:  Iter 35/35 - Loss: 0.095 (delta=-0.020367)

  cell_5_1: 15000 pts, 35 iters, final loss = 0.0954

[2026-04-28 00:33:50,378] INFO:  Iter 1/35 - Loss: 0.766 (delta=inf)
[2026-04-28 00:33:51,895] INFO:  Iter 2/35 - Loss: 0.748 (delta=-0.018222)
[2026-04-28 00:33:53,512] INFO:  Iter 3/35 - Loss: 0.729 (delta=-0.018891)
[2026-04-28 00:33:55,098] INFO:  Iter 4/35 - Loss: 0.710 (delta=-0.018648)
[2026-04-28 00:33:56,966] INFO:  Iter 5/35 - Loss: 0.692 (delta=-0.018626)
[2026-04-28 00:33:58,525] INFO:  Iter 6/35 - Loss: 0.673 (delta=-0.018754)
[2026-04-28 00:34:00,813] INFO:  Iter 7/35 - Loss: 0.654 (delta=-0.019001)
[2026-04-28 00:34:02,404] INFO:  Iter 8/35 - Loss: 0.635 (delta=-0.018904)
[2026-04-28 00:34:03,957] INFO:  Iter 9/35 - Loss: 0.616 (delta=-0.018493)
[2026-04-28 00:34:05,537] INFO:  Iter 10/35 - Loss: 0.597 (delta=-0.019637)
[2026-04-28 00:34:07,086] INFO:  Iter 11/35 - Loss: 0.578 (delta=-0.019117)
[2026-04-28 00:34:08,659] INFO:  Iter 12/35 - Loss: 0.558 (delta=-0.019543)
[2026-04-28 00:34:10,196] INFO:  Iter 13/35 - Loss: 0.539 (delta=-0.018981)
[2026-04-28 00:34:12,063] INFO:  Iter 14/35 - Loss: 0.520 (delta=-0.019447)
[2026-04-28 00:34:13,632] INFO:  Iter 15/35 - Loss: 0.500 (delta=-0.020114)
[2026-04-28 00:34:15,132] INFO:  Iter 16/35 - Loss: 0.480 (delta=-0.019852)
[2026-04-28 00:34:16,732] INFO:  Iter 17/35 - Loss: 0.460 (delta=-0.019396)
[2026-04-28 00:34:18,287] INFO:  Iter 18/35 - Loss: 0.440 (delta=-0.019970)
[2026-04-28 00:34:20,139] INFO:  Iter 19/35 - Loss: 0.420 (delta=-0.020346)
[2026-04-28 00:34:21,716] INFO:  Iter 20/35 - Loss: 0.400 (delta=-0.020136)
[2026-04-28 00:34:23,265] INFO:  Iter 21/35 - Loss: 0.380 (delta=-0.019966)
[2026-04-28 00:34:24,775] INFO:  Iter 22/35 - Loss: 0.359 (delta=-0.020729)
[2026-04-28 00:34:26,276] INFO:  Iter 23/35 - Loss: 0.339 (delta=-0.020648)
[2026-04-28 00:34:27,786] INFO:  Iter 24/35 - Loss: 0.318 (delta=-0.020458)
[2026-04-28 00:34:29,346] INFO:  Iter 25/35 - Loss: 0.297 (delta=-0.020684)
[2026-04-28 00:34:31,942] INFO:  Iter 26/35 - Loss: 0.277 (delta=-0.020460)
[2026-04-28 00:34:33,576] INFO:  Iter 27/35 - Loss: 0.257 (delta=-0.020261)
[2026-04-28 00:34:35,083] INFO:  Iter 28/35 - Loss: 0.236 (delta=-0.020876)
[2026-04-28 00:34:36,740] INFO:  Iter 29/35 - Loss: 0.216 (delta=-0.020235)
[2026-04-28 00:34:38,312] INFO:  Iter 30/35 - Loss: 0.194 (delta=-0.021382)
[2026-04-28 00:34:39,834] INFO:  Iter 31/35 - Loss: 0.173 (delta=-0.021034)
[2026-04-28 00:34:41,346] INFO:  Iter 32/35 - Loss: 0.153 (delta=-0.019973)
[2026-04-28 00:34:42,869] INFO:  Iter 33/35 - Loss: 0.132 (delta=-0.020942)
[2026-04-28 00:34:44,410] INFO:  Iter 34/35 - Loss: 0.111 (delta=-0.021000)
[2026-04-28 00:34:46,005] INFO:  Iter 35/35 - Loss: 0.090 (delta=-0.021075)

  cell_5_2: 15000 pts, 35 iters, final loss = 0.0902

[2026-04-28 00:34:47,610] INFO:  Iter 1/35 - Loss: 0.768 (delta=inf)
[2026-04-28 00:34:49,138] INFO:  Iter 2/35 - Loss: 0.750 (delta=-0.018262)
[2026-04-28 00:34:50,675] INFO:  Iter 3/35 - Loss: 0.732 (delta=-0.018355)
[2026-04-28 00:34:52,213] INFO:  Iter 4/35 - Loss: 0.713 (delta=-0.018452)
[2026-04-28 00:34:53,762] INFO:  Iter 5/35 - Loss: 0.695 (delta=-0.018445)
[2026-04-28 00:34:55,320] INFO:  Iter 6/35 - Loss: 0.677 (delta=-0.018187)
[2026-04-28 00:34:57,574] INFO:  Iter 7/35 - Loss: 0.658 (delta=-0.018700)
[2026-04-28 00:34:59,190] INFO:  Iter 8/35 - Loss: 0.639 (delta=-0.018869)
[2026-04-28 00:35:01,626] INFO:  Iter 9/35 - Loss: 0.620 (delta=-0.018667)
[2026-04-28 00:35:03,180] INFO:  Iter 10/35 - Loss: 0.602 (delta=-0.018821)
[2026-04-28 00:35:04,707] INFO:  Iter 11/35 - Loss: 0.583 (delta=-0.019076)
[2026-04-28 00:35:06,210] INFO:  Iter 12/35 - Loss: 0.564 (delta=-0.018984)
[2026-04-28 00:35:07,800] INFO:  Iter 13/35 - Loss: 0.544 (delta=-0.019280)
[2026-04-28 00:35:09,346] INFO:  Iter 14/35 - Loss: 0.525 (delta=-0.019043)
[2026-04-28 00:35:10,865] INFO:  Iter 15/35 - Loss: 0.506 (delta=-0.019337)
[2026-04-28 00:35:12,397] INFO:  Iter 16/35 - Loss: 0.486 (delta=-0.019717)
[2026-04-28 00:35:13,954] INFO:  Iter 17/35 - Loss: 0.467 (delta=-0.019457)
[2026-04-28 00:35:16,088] INFO:  Iter 18/35 - Loss: 0.447 (delta=-0.019530)
[2026-04-28 00:35:17,666] INFO:  Iter 19/35 - Loss: 0.428 (delta=-0.019721)
[2026-04-28 00:35:19,243] INFO:  Iter 20/35 - Loss: 0.408 (delta=-0.019696)
[2026-04-28 00:35:20,800] INFO:  Iter 21/35 - Loss: 0.388 (delta=-0.019879)
[2026-04-28 00:35:22,399] INFO:  Iter 22/35 - Loss: 0.368 (delta=-0.020262)
[2026-04-28 00:35:23,968] INFO:  Iter 23/35 - Loss: 0.348 (delta=-0.019302)
[2026-04-28 00:35:25,491] INFO:  Iter 24/35 - Loss: 0.328 (delta=-0.020317)
[2026-04-28 00:35:27,033] INFO:  Iter 25/35 - Loss: 0.308 (delta=-0.020533)
[2026-04-28 00:35:28,543] INFO:  Iter 26/35 - Loss: 0.288 (delta=-0.019847)
[2026-04-28 00:35:30,798] INFO:  Iter 27/35 - Loss: 0.267 (delta=-0.020199)
[2026-04-28 00:35:32,453] INFO:  Iter 28/35 - Loss: 0.248 (delta=-0.019461)
[2026-04-28 00:35:34,000] INFO:  Iter 29/35 - Loss: 0.228 (delta=-0.019906)
[2026-04-28 00:35:36,575] INFO:  Iter 30/35 - Loss: 0.208 (delta=-0.020374)
[2026-04-28 00:35:39,300] INFO:  Iter 31/35 - Loss: 0.188 (delta=-0.019689)
[2026-04-28 00:35:41,057] INFO:  Iter 32/35 - Loss: 0.169 (delta=-0.019545)
[2026-04-28 00:35:42,640] INFO:  Iter 33/35 - Loss: 0.148 (delta=-0.020624)
[2026-04-28 00:35:44,186] INFO:  Iter 34/35 - Loss: 0.128 (delta=-0.019401)
[2026-04-28 00:35:45,714] INFO:  Iter 35/35 - Loss: 0.109 (delta=-0.019257)

  cell_5_3: 15000 pts, 35 iters, final loss = 0.1092

Bayesian total time: 1175.07s

## 6. Train SVGPDigitalTwin

In [ ]:
min_train_svgp = min(len(df) for df in train_list_svgp)
svgp_config = SVGPTrainConfig(
    num_inducing=min(1000, min_train_svgp),
    batch_size=2048,
    num_epochs=100,
    learning_rate=0.01,
    ngd_lr=0.1,
    stopping_threshold=1e-4,
    inducing_init="kmeans++",
    seed=42,
    log_every=1,
    multicell_batched=True,  # batched multi-cell SVGP via IndependentMultitaskVariationalStrategy
)
mode_str = "multicell batched (MultiCellSVGPModel)" if svgp_config.multicell_batched else "per-cell sequential"
print(
    f"SVGP config: {svgp_config.num_inducing} inducing pts, "
    f"batch={svgp_config.batch_size}, epochs={svgp_config.num_epochs}, "
    f"init={svgp_config.inducing_init}"
)
print(f"SVGP mode   : {mode_str}")
print(f"SVGP full train rows: {sum(len(df) for df in train_list_svgp):,}")

svgp_model = SVGPDigitalTwin(x_max=x_max, x_min=x_min, device="cpu")

t0 = time.time()
svgp_loss_matrix = svgp_model.train(train_list_svgp, X_COLUMNS, Y_COLUMNS, svgp_config)
svgp_train_time = time.time() - t0

svgp_cell_ids = list(svgp_model._cell_ids)
svgp_losses = {
    cid: svgp_loss_matrix[i][np.isfinite(svgp_loss_matrix[i])]
    for i, cid in enumerate(svgp_cell_ids)
}

for cid in svgp_cell_ids:
    print(
        f"  {cid}: {len(train_map_svgp[cid]):>6,} pts, {len(svgp_losses[cid])} epochs, "
        f"final loss = {svgp_losses[cid][-1]:.4f}"
    )
print(f"\nSVGP total time: {svgp_train_time:.2f}s")


def predict_bayesian_cell(cell_id: str, frame: pd.DataFrame):
    if not RUN_BAYESIAN:
        n = len(frame)
        return np.full(n, np.nan), np.full(n, np.nan)
    means, stds = bayesian_model_map[cell_id].predict_distributed_gpmodel([frame.copy()])
    return means[0], stds[0]

## 7. Training loss curves

In [13]:
cell_ids = sorted(test_map.keys())
n_cells = len(cell_ids)
fig, axes = plt.subplots(1, n_cells, figsize=(5 * n_cells, 4))
if n_cells == 1:
    axes = [axes]

for ax, cid in zip(axes, cell_ids):
    if RUN_BAYESIAN:
        ax.plot(bayesian_losses[cid], "b-o", markersize=3, label="Bayesian (Exact MLL)")
    ax.plot(svgp_losses[cid], "r-s", markersize=3, label="SVGP (Variational ELBO)")
    ax.set_title(cid)
    ax.set_xlabel("Iter / Epoch")
    ax.set_ylabel("Loss")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

fig.suptitle("Training Loss Curves", fontsize=13)
plt.tight_layout()
plt.show()

## 8. Prediction — MAE and MAPE

In [14]:
results = []
pred_cache = {}

# Full SVGP test evaluation in one call. With the full Million dataset this is
# 20 frames x 15,000 rows = 300,000 held-out predictions.
ordered_test_frames = [test_map[cid].copy() for cid in svgp_cell_ids]
svgp_test_means, svgp_test_stds = svgp_model.predict(ordered_test_frames)

for idx, cell_id in enumerate(svgp_cell_ids):
    true_rsrp = test_map[cell_id]["avg_rsrp"].values
    svgp_m = svgp_test_means[:, idx]
    svgp_s = svgp_test_stds[:, idx]
    bay_m, bay_s = predict_bayesian_cell(cell_id, test_map[cell_id])
    pred_cache[cell_id] = {
        "bay_m": bay_m,
        "bay_s": bay_s,
        "svgp_m": svgp_m,
        "svgp_s": svgp_s,
    }

    row = {
        "cell_id": cell_id,
        "n_train_bdt": len(train_map_bdt[cell_id]),
        "n_train_svgp": len(train_map_svgp[cell_id]),
        "n_test": len(test_map[cell_id]),
        "svgp_mae_db": round(float(np.abs(true_rsrp - svgp_m).mean()), 3),
        "svgp_mape_%": round(float((100 * np.abs((true_rsrp - svgp_m) / true_rsrp)).mean()), 2),
        "svgp_uncertainty_db": round(float(svgp_s.mean()), 3),
    }
    if RUN_BAYESIAN:
        row.update({
            "bayesian_mae_db": round(float(np.abs(true_rsrp - bay_m).mean()), 3),
            "bayesian_mape_%": round(float((100 * np.abs((true_rsrp - bay_m) / true_rsrp)).mean()), 2),
            "bayesian_uncertainty_db": round(float(bay_s.mean()), 3),
        })
    results.append(row)

results_df = pd.DataFrame(results).set_index("cell_id")
results_df

,n_train_bdt,n_train_svgp,n_test,svgp_mae_db,svgp_mape_%,svgp_uncertainty_db,bayesian_mae_db,bayesian_mape_%,bayesian_uncertainty_db
cell_id,,,,,,,,,
cell_1_0,15000,35000,15000,1.857,2.49,5.267,1.832,2.46,11.016
cell_1_1,15000,35000,15000,1.783,2.42,5.434,1.809,2.41,10.669
cell_1_2,15000,35000,15000,1.572,2.17,4.669,1.733,2.24,11.101
cell_1_3,15000,35000,15000,2.135,2.88,5.339,1.875,2.51,10.930
cell_2_0,15000,35000,15000,1.325,1.69,3.752,1.250,1.63,8.975
cell_2_1,15000,35000,15000,1.385,1.76,3.716,1.276,1.66,9.044
cell_2_2,15000,35000,15000,1.324,1.69,3.694,1.359,1.69,8.989
cell_2_3,15000,35000,15000,1.285,1.61,3.539,1.362,1.66,9.047
cell_3_0,15000,35000,15000,1.983,2.58,5.429,2.077,2.65,10.484
cell_3_1,15000,35000,15000,2.575,3.03,5.841,1.982,2.57,10.404
cell_3_2,15000,35000,15000,1.870,2.48,5.384,2.000,2.57,10.639
cell_3_3,15000,35000,15000,1.615,2.24,4.409,1.570,2.21,11.603
cell_4_0,15000,35000,15000,1.929,2.44,5.281,1.896,2.37,10.389
cell_4_1,15000,35000,15000,1.764,2.47,4.760,1.587,2.13,11.305
cell_4_2,15000,35000,15000,1.918,2.58,5.240,1.896,2.55,10.959
cell_4_3,15000,35000,15000,1.873,2.40,5.278,1.972,2.45,10.460
cell_5_0,15000,35000,15000,1.280,1.62,3.653,1.429,1.73,9.198
cell_5_1,15000,35000,15000,1.243,1.53,3.528,1.456,1.66,9.101
cell_5_2,15000,35000,15000,1.394,1.73,3.724,1.252,1.62,9.601
cell_5_3,15000,35000,15000,1.280,1.55,3.723,1.476,1.68,8.936

In [ ]:
print("=== Summary ===")
if RUN_BAYESIAN:
    print(f"Bayesian avg MAE : {results_df['bayesian_mae_db'].mean():.3f} dB")
print(f"SVGP     avg MAE : {results_df['svgp_mae_db'].mean():.3f} dB")
if RUN_BAYESIAN:
    print(f"Bayesian time    : {bayesian_train_time:.2f}s")
mode_str = "multicell batched (MultiCellSVGPModel)" if svgp_config.multicell_batched else "per-cell sequential"
print(f"SVGP time        : {svgp_train_time:.2f}s")
print(f"SVGP mode        : {mode_str}")
print(f"Num cells        : {len(svgp_cell_ids)}")
results_df

## 9. Side-by-side scatter: True vs Predicted RSRP

In [ ]:
cell_ids = sorted(test_map.keys())
n_cells = len(cell_ids)
fig, axes = plt.subplots(1, n_cells, figsize=(5 * n_cells, 4))
if n_cells == 1:
    axes = [axes]

for ax, cid in zip(axes, cell_ids):
    true_r = test_map[cid]["avg_rsrp"].values
    sm = pred_cache[cid]["svgp_m"]
    series = [true_r, sm]
    labels = ["SVGP"]
    if RUN_BAYESIAN:
        bm = pred_cache[cid]["bay_m"]
        series.append(bm)
        labels.insert(0, "Bayesian")
    lim = [min(arr.min() for arr in series) - 2, max(arr.max() for arr in series) + 2]
    ax.plot(lim, lim, "k--", lw=1, alpha=0.5, label="Perfect")
    if RUN_BAYESIAN:
        ax.scatter(true_r, pred_cache[cid]["bay_m"], alpha=0.5, s=10, c="steelblue", label="Bayesian")
    ax.scatter(true_r, sm, alpha=0.5, s=10, c="tomato", marker="s", label="SVGP")
    r = results_df.loc[cid]
    title = f"{cid}\nSVGP={r['svgp_mae_db']}dB MAE"
    if RUN_BAYESIAN:
        title = f"{cid}\nBay={r['bayesian_mae_db']}dB | SVGP={r['svgp_mae_db']}dB MAE"
    ax.set_title(title)
    ax.set_xlabel("True RSRP (dBm)")
    ax.set_ylabel("Predicted (dBm)")
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)
    ax.set_xlim(lim)
    ax.set_ylim(lim)

fig.suptitle("True vs Predicted RSRP", fontsize=13)
plt.tight_layout()
plt.show()

:

## 10. Uncertainty calibration — ±2σ bands vs log_distance

In [ ]:
cell_ids = sorted(test_map.keys())
n_cells = len(cell_ids)
fig, axes = plt.subplots(1, n_cells, figsize=(5 * n_cells, 4))
if n_cells == 1:
    axes = [axes]

for ax, cid in zip(axes, cell_ids):
    tdf = test_map[cid].copy()
    sort_idx = tdf[c.LOG_DISTANCE].argsort().values
    tdf_sorted = tdf.iloc[sort_idx].reset_index(drop=True)

    # Reuse predictions already computed in cell-21 — no extra predict calls needed.
    sm = pred_cache[cid]["svgp_m"][sort_idx]
    ss = pred_cache[cid]["svgp_s"][sort_idx]

    x = tdf_sorted[c.LOG_DISTANCE].values
    ax.scatter(x, tdf_sorted["avg_rsrp"].values, c="black", s=6, zorder=5, label="Measured")
    if RUN_BAYESIAN:
        bm = pred_cache[cid]["bay_m"][sort_idx]
        bs = pred_cache[cid]["bay_s"][sort_idx]
        ax.plot(x, bm, "b-", lw=1.5, label="Bayesian")
        ax.fill_between(x, bm - 2 * bs, bm + 2 * bs, alpha=0.15, color="blue")
    ax.plot(x, sm, "r--", lw=1.5, label="SVGP")
    ax.fill_between(x, sm - 2 * ss, sm + 2 * ss, alpha=0.15, color="red")
    ax.set_xlabel("log_distance")
    ax.set_ylabel("RSRP (dBm)")
    ax.set_title(f"{cid} - +/-2 sigma")
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)

fig.suptitle("Prediction Uncertainty", fontsize=13)
plt.tight_layout()
plt.show()

## 11. RSRP coverage heatmap (SVGP)

In [ ]:
GRID_N = 40
grid_lats = np.linspace(LAT_MIN, LAT_MAX, GRID_N)
grid_lons = np.linspace(LON_MIN, LON_MAX, GRID_N)
LON_GRID, LAT_GRID = np.meshgrid(grid_lons, grid_lats)

grid_template = pd.DataFrame({c.LOC_X: LON_GRID.ravel(), c.LOC_Y: LAT_GRID.ravel()})
prediction_frames = SVGPDigitalTwin.create_prediction_frames(site_configs_demo, grid_template)
ordered_grid_frames = [prediction_frames[cid] for cid in svgp_cell_ids]
means, _ = svgp_model.predict(ordered_grid_frames)

best_rsrp = means.max(axis=1)
rsrp_map = best_rsrp.reshape(GRID_N, GRID_N)
print(f"Predicted RSRP: {rsrp_map.min():.1f} to {rsrp_map.max():.1f} dBm")

In [ ]:
fig, ax = plt.subplots(figsize=(9, 7))
im = ax.pcolormesh(LON_GRID, LAT_GRID, rsrp_map,
                   cmap="RdYlGn", vmin=-120, vmax=-50, shading="auto")
plt.colorbar(im, ax=ax, label="Best-cell RSRP (dBm)")

colors = ["#e74c3c", "#3498db", "#2ecc71", "#f39c12"]
for (_, row), color in zip(site_configs_demo.iterrows(), colors):
    ax.scatter(row.cell_lon, row.cell_lat, s=250, marker="^",
               c=color, edgecolors="black", linewidths=1.5, zorder=10, label=row.cell_id)

ax.scatter(ue_data_df["lon"], ue_data_df["lat"],
           c=ue_data_df["avg_rsrp"], cmap="RdYlGn", vmin=-120, vmax=-50,
           s=5, alpha=0.4, edgecolors="none", zorder=5)

ax.set_xlabel("Longitude"); ax.set_ylabel("Latitude")
ax.set_title(f"SVGP Digital Twin — Best-Cell RSRP Coverage\n"
             f"{DEMO_SITE} ({len(demo_cell_ids)} cells, Mobility Data)")
ax.legend(loc="upper right", fontsize=9)
plt.tight_layout(); plt.show()

## 12. Save / load model (torch.save, no pickle)

In [ ]:
import os
import tempfile

with tempfile.NamedTemporaryFile(suffix=".pt", delete=False) as f:
    path = f.name

svgp_model.save(path)
file_kb = os.path.getsize(path) / 1024
print(f"Saved SVGP model: {file_kb:.1f} KB -> {path}")

loaded = SVGPDigitalTwin.load(path, map_location="cpu")
multicell_mode = getattr(loaded, "_multicell_batched", False)
print(
    f"Loaded: is_trained={loaded.is_trained}, "
    f"cell_ids={loaded._cell_ids}, "
    f"multicell_batched={multicell_mode}"
)

check_frames = [test_map[cid].head(50).copy() for cid in svgp_cell_ids]
orig_m, _ = svgp_model.predict([frame.copy() for frame in check_frames])
load_m, _ = loaded.predict([frame.copy() for frame in check_frames])
diff = np.abs(orig_m - load_m).max()
print(f"Max prediction diff post-load: {diff:.6f} dB  {'OK' if diff < 0.01 else 'DIFF LARGE'}")
os.unlink(path)

## 14. When does SVGP outperform Bayesian? — Scaling analysis

In [ ]:
print("""
╔══════════════════════════════════════════════════════════════════════════╗
║              SVGP vs Bayesian: Accuracy & Scalability                   ║
╠══════════════╦══════════════════════╦══════════════════════════════════╣
║ n pts/cell   ║ Bayesian (ExactGP)   ║ SVGP (m=500 inducing)            ║
╠══════════════╬══════════════════════╬══════════════════════════════════╣
║ 50           ║ BEST accuracy, fast  ║ Good — slight variance overhead  ║
║ 500          ║ Good, 0.1-2s/cell    ║ Good — on par within ~2-5% MAE  ║
║ 5,000        ║ ~60s/cell (slow!)    ║ ~5s/cell — 12x faster           ║
║ 50,000       ║ OOM / hours          ║ ~50s/cell — still feasible      ║
║ 500,000      ║ Impossible           ║ ~8min/cell — works               ║
╚══════════════╩══════════════════════╩══════════════════════════════════╝

Key insight:
  • SVGP is a variational APPROXIMATION to ExactGP.
  • On small n (like this notebook), Bayesian is marginally more accurate.
  • SVGP's real advantage: it CAN RUN on real deployment data where Bayesian
    completely fails (O(n³) Cholesky → OOM or hours).
  • With m ≈ 500 inducing points and n ≈ 5K-50K/cell, SVGP MAE is within
    2-5% of ExactGP — practically indistinguishable in production.
  • Both models use the same kernel family, so the accuracy ceiling is the
    same; SVGP just reaches it with O(n·m²) instead of O(n³).
""")

## 15. DTModel interface summary

In [ ]:
print(f"SVGPDigitalTwin is DTModel: {isinstance(svgp_model, DTModel)}")
print(f"SVGP model_type: {svgp_model.model_type}")
print()
print("Current SVGP interface:")
print("  model.train(data_in, x_columns, y_columns, config)")
print("  model.predict(prediction_dfs) -> (means, stds)")
print("  model.save(path)              -> torch.save checkpoint")
print("  SVGPDigitalTwin.load(path)    -> restored model")
print("  model.is_trained              -> bool")
print("  model.model_type              -> str")